PSBOVT ;BIRMINGHAM/BSR-CUMULATIVE VITALS REPORT ;Mar 2004
 ;;3.0;BAR CODE MED ADMIN;;Mar 2004;
 ; Reference/IA
 ; EN3^GMRVSC0/1444
 ;
EN ; Print Cumulative Vitals Report
 ;
 N PSBGBL,DFN
 S PSBGBL="^TMP(""PSBO"",$J,""B"")"
 S PSBGBL=$Q(@PSBGBL) Q:PSBGBL=""  Q:$QS(PSBGBL,1)'="PSBO"!($QS(PSBGBL,2)'=$J)
 S DFN=$QS(PSBGBL,5)
 D PRNT(DFN,$P(PSBRPT(.1),U,6)_$P(PSBRPT(.1),U,7),$P(PSBRPT(.1),U,8)_$P(PSBRPT(.1),U,9))
 Q
 ;
PRNT(DFN,PSBVSDT,PSBVFDT)             ; PATIENT CUMULATIVE VITALS REPORT
 ; INPUT VARIABLES:    DFN=PATIENT NUMBER
 ;
 S FLGD=""
 S PSBINS=$P(PSBVSDT,".")
 S PSBINSA=$P(PSBVFDT,".")
 D DATEADD
 I IOST="P-DUMMY"  D PSBIOCH
 D EN3^GMRVSC0(DFN,PSBINS,PSBINSA)
 Q
 ;
DATEADD ;
 S X=PSBINSA
 D H^%DTC
 S %H=%H+1
 D YMD^%DTC
 S PSBINSA=X
 Q
 ;
PSBIOCH ;
 S IOF="#"
 S IOSL="66"
 Q
 ;
 ;
