PPPP43  ;BHM/DB - RETIRING PPP ;3/20/08
        ;;1.0;PHARMACY PRESCRIPTION PRACTICE;**43**;APR 7,1995;Build 2
        ;
        D BMES^XPDUTL("Marking all Pharmacy Prescription Practices options as OUT OF ORDER PER PSI-07-114.")
        ;
        D OUT^XPDMENU("PPP (EDIT) PARAMETER","OPTION RETIRED BY PATCH PPP*1*43 AS PER PSI-07-114")
        D OUT^XPDMENU("PPP BACKGROUND PURGE LOGFILE","OPTION RETIRED BY PATCH PPP*1*43 AS PER PSI-07-114")
        D OUT^XPDMENU("PPP BACKGROUND PURGE XREF","OPTION RETIRED BY PATCH PPP*1*43 AS PER PSI-07-114")
        D OUT^XPDMENU("PPP BATCH","OPTION RETIRED BY PATCH PPP*1*43 AS PER PSI-07-114")
        D OUT^XPDMENU("PPP BUILD FFX","OPTION RETIRED BY PATCH PPP*1*43 AS PER PSI-07-114")
        D OUT^XPDMENU("PPP DISPLAY FOREIGN VISITS","OPTION RETIRED BY PATCH PPP*1*43 AS PER PSI-07-114")
        D OUT^XPDMENU("PPP EDIT DOMAIN","OPTION RETIRED BY PATCH PPP*1*43 AS PER PSI-07-114")
        D OUT^XPDMENU("PPP EDIT FFX","OPTION RETIRED BY PATCH PPP*1*43 AS PER PSI-07-114")
        D OUT^XPDMENU("PPP INIT PURGE LOGFILE JOB","OPTION RETIRED BY PATCH PPP*1*43 AS PER PSI-07-114")
        D OUT^XPDMENU("PPP INIT PURGE XREF JOB","OPTION RETIRED BY PATCH PPP*1*43 AS PER PSI-07-114")
        D OUT^XPDMENU("PPP INIT STAT","OPTION RETIRED BY PATCH PPP*1*43 AS PER PSI-07-114")
        D OUT^XPDMENU("PPP MAIN","OPTION RETIRED BY PATCH PPP*1*43 AS PER PSI-07-114")
        D OUT^XPDMENU("PPP MERGED SITE EDIT","OPTION RETIRED BY PATCH PPP*1*43 AS PER PSI-07-114")
        D OUT^XPDMENU("PPP PRINT CLINIC PROFILES","OPTION RETIRED BY PATCH PPP*1*43 AS PER PSI-07-114")
        D OUT^XPDMENU("PPP PRINT FFX","OPTION RETIRED BY PATCH PPP*1*43 AS PER PSI-07-114")
        D OUT^XPDMENU("PPP PRINT LOG","OPTION RETIRED BY PATCH PPP*1*43 AS PER PSI-07-114")
        D OUT^XPDMENU("PPP PRINT STATISTICS","OPTION RETIRED BY PATCH PPP*1*43 AS PER PSI-07-114")
        D OUT^XPDMENU("PPP PURGE LOGFILE","OPTION RETIRED BY PATCH PPP*1*43 AS PER PSI-07-114")
        D OUT^XPDMENU("PPP PURGE LOGFILE MENU","OPTION RETIRED BY PATCH PPP*1*43 AS PER PSI-07-114")
        D OUT^XPDMENU("PPP PURGE XREF MENU","OPTION RETIRED BY PATCH PPP*1*43 AS PER PSI-07-114")
        D OUT^XPDMENU("PPP XREF PURGE","OPTION RETIRED BY PATCH PPP*1*43 AS PER PSI-07-114")
        Q
