PPPPRT10 ;ALB/JFP - DISPLAY LOG FILE BY DATE ; 3/20/92
 ;;V1.0;PHARMACY PRESCRIPTION PRACTICE;;APR 7,1995
 ;;Per VHA Directive 10-93-142, this routine should not be modified.
 ;
DSPLOG ;
 ;
 N IDATE,DONE,TMP,BNR1
 ;
 S (IDATE,DONE)=0
 S BNR1="PHARMACY PRESCRIPTION PRACTICES PRINT LOG"
 ;
 F IDATE=0:0 D  Q:+IDATE<0!(DONE)
 .S TMP=$$BANNER^PPPDSP1(BNR1) W !!
 .S IDATE=$$GETDATE^PPPPRT10()
 .I IDATE<0 S DONE=1 Q
 .D DSPLOG^PPPPRT11(IDATE)
 Q
 ;
GETDATE() ; Prompts for date
 S DIR("A")="Enter Date: "
 ;S DIR("B")=""
 S DIR(0)="DAO^:@DT:EX"
 D ^DIR K DIR
 I $D(DIRUT)!$D(DTOUT)!$D(DUOUT) Q -1
 S IDATE=Y
 Q IDATE
 ;
