RTCP ; GENERATED FROM 'RT PULL LIST' INPUT TEMPLATE(#892), FILE 194.2;09/19/10
 D DE G BEGIN
DE S DIE="^RTV(194.2,",DIC=DIE,DP=194.2,DL=1,DIEL=0,DU="" K DG,DE,DB Q:$O(^RTV(194.2,DA,""))=""
 I $D(^(0)) S %Z=^(0) S %=$P(%Z,U,1) S:%]"" DE(3)=% S %=$P(%Z,U,2) S:%]"" DE(16)=%,DE(19)=% S %=$P(%Z,U,3) S:%]"" DE(21)=% S %=$P(%Z,U,4) S:%]"" DE(8)=%,DE(13)=% S %=$P(%Z,U,5) S:%]"" DE(23)=%,DE(27)=% S %=$P(%Z,U,6) S:%]"" DE(37)=%
 I  S %=$P(%Z,U,7) S:%]"" DE(38)=% S %=$P(%Z,U,8) S:%]"" DE(39)=% S %=$P(%Z,U,10) S:%]"" DE(36)=% S %=$P(%Z,U,11) S:%]"" DE(10)=% S %=$P(%Z,U,12) S:%]"" DE(31)=%,DE(34)=%
 K %Z Q
 ;
W W !?DL+DL-2,DLB_": "
 Q
O D W W Y W:$X>45 !?9
 I $L(Y)>19,'DV,DV'["I",(DV["F"!(DV["K")) G RW^DIR2
 W:Y]"" "// " I 'DV,DV["I",$D(DE(DQ))#2 S X="" W "  (No Editing)" Q
TR R X:DTIME E  S (DTOUT,X)=U W $C(7)
 Q
A K DQ(DQ) S DQ=DQ+1
B G @DQ
RE G PR:$D(DE(DQ)) D W,TR
N I X="" G NKEY:$D(^DD("KEY","F",DP,DIFLD)),A:DV'["R",X:'DV,X:D'>0,A
RD G QS:X?."?" I X["^" D D G ^DIE17
 I X="@" D D G Z^DIE2
 I X=" ",DV["d",DV'["P",$D(^DISV(DUZ,"DIE",DLB)) S X=^(DLB) I DV'["D",DV'["S" W "  "_X
T G M^DIE17:DV,^DIE3:DV["V",P:DV'["S" X:$D(^DD(DP,DIFLD,12.1)) ^(12.1) I X?.ANP D SET I 'DDER X:$D(DIC("S")) DIC("S") I  W:'$D(DB(DQ)) "  "_% G V
 K DDER G X
P I DV["P" S DIC=U_DU,DIC(0)=$E("EN",$D(DB(DQ))+1)_"M"_$E("L",DV'["'") S:DIC(0)["L" DLAYGO=+$P(DV,"P",2) G:DV["*" AST^DIED D NOSCR^DIED S X=+Y,DIC=DIE G X:X<0
 G V:DV'["N" D D I $L($P(X,"."))>24 K X G Z
 I $P(DQ(DQ),U,5)'["$",X?.1"-".N.1".".N,$P(DQ(DQ),U,5,99)["+X'=X" S X=+X
V D @("X"_DQ) K YS
Z K DIC("S"),DLAYGO I $D(X),X'=U D:$G(DE(DW,"INDEX")) SAVEVALS G:'$$KEYCHK UNIQFERR^DIE17 S DG(DW)=X S:DV["d" ^DISV(DUZ,"DIE",DLB)=X G A
X W:'$D(ZTQUEUED) $C(7),"??" I $D(DB(DQ)) G Z^DIE17
 S X="?BAD"
QS S DZ=X D D,QQ^DIEQ G B
D S D=DIFLD,DQ(DQ)=DLB_U_DV_U_DU_U_DW_U_$P($T(@("X"_DQ))," ",2,99) Q
Y I '$D(DE(DQ)) D O G RD:"@"'[X,A:DV'["R"&(X="@"),X:X="@" S X=Y G N
PR S DG=DV,Y=DE(DQ),X=DU I $D(DQ(DQ,2)) X DQ(DQ,2) G RP
R I DG["P",@("$D(^"_X_"0))") S X=+$P(^(0),U,2) G RP:'$D(^(Y,0)) S Y=$P(^(0),U),X=$P(^DD(X,.01,0),U,3),DG=$P(^(0),U,2) G R
 I DG["V",+Y,$P(Y,";",2)["(",$D(@(U_$P(Y,";",2)_"0)")) S X=+$P(^(0),U,2) G RP:'$D(^(+Y,0)) S Y=$P(^(0),U) I $D(^DD(+X,.01,0)) S DG=$P(^(0),U,2),X=$P(^(0),U,3) G R
 X:DG["D" ^DD("DD") I DG["S" S %=$P($P(";"_X,";"_Y_":",2),";") S:%]"" Y=%
RP D O I X="" S X=DE(DQ) G A:'DV,A:DC<2,N^DIE17
I I DV'["I",DV'["#" G RD
 D E^DIE0 G RD:$D(X),PR
 Q
SET N DIR S DIR(0)="SV"_$E("o",$D(DB(DQ)))_U_DU,DIR("V")=1
 I $D(DB(DQ)),'$D(DIQUIET) N DIQUIET S DIQUIET=1
 D ^DIR I 'DDER S %=Y(0),X=Y
 Q
SAVEVALS S @DIEZTMP@("V",DP,DIIENS,DIFLD,"O")=$G(DE(DQ)) S:$D(^("F"))[0 ^("F")=$G(DE(DQ))
 I $D(DE(DW,"4/")) S @DIEZTMP@("V",DP,DIIENS,DIFLD,"4/")=""
 E  K @DIEZTMP@("V",DP,DIIENS,DIFLD,"4/")
 Q
NKEY W:'$D(ZTQUEUED) "??  Required key field" S X="?BAD" G QS
KEYCHK() Q:$G(DE(DW,"KEY"))="" 1 Q @DE(DW,"KEY")
BEGIN S DNM="RTCP",DQ=1
 N DIEZTMP,DIEZAR,DIEZRXR,DIIENS,DIXR K DIEFIRE,DIEBADK S DIEZTMP=$$GETTMP^DIKC1("DIEZ")
 M DIEZAR=^DIE(892,"AR") S DICRREC="TRIG^DIE17"
 S:$D(DTIME)[0 DTIME=300 S D0=DA,DIIENS=DA_",",DIEZ=892,U="^"
1 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=1 D X1 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X1 S RTSEMI=$C(59) D DUZ^RTPSET
 Q
2 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=2 D X2 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X2 S:'$D(RTSHOW) Y="@10"
 Q
3 S DW="0;1",DV="RFX",DU="",DLB="PULL LIST",DIFLD=.01
 S DE(DW)="C3^RTCP"
 G RE
C3 G C3S:$D(DE(3))[0 K DB
 S X=DE(3),DIC=DIE
 K ^RTV(194.2,"B",$E(X,1,45),DA)
C3S S X="" G:DG(DQ)=X C3F1 K DB
 S X=DG(DQ),DIC=DIE
 S ^RTV(194.2,"B",$E(X,1,45),DA)=""
C3F1 Q
X3 K:$L(X)>45!($L(X)<3) X I $D(X) S X=$$UP^XLFSTR(X)
 I $D(X),X'?.ANP K X
 Q
 ;
4 D:$D(DG)>9 F^DIE17,DE S DQ=4,D=0 K DE(1) ;100
 S Y="COMMENTS^W^^0;1^Q",DG="1",DC="^194.21" D DIEN^DIWE K DE(1) G A
 ;
5 S DQ=6 ;@10
6 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=6 D X6 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X6 S:$D(RTTY) Y="@15"
 Q
7 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=7 D X7 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X7 I $D(RTPLTY),"13"[$E(RTPLTY_0) S Y="@18"
 Q
8 S DW="0;4",DV="*P195.2'",DU="",DLB="RECORD TYPE RESTRICTION",DIFLD=4
 S DU="DIC(195.2,"
 G RE
X8 S DIC("S")="I $D(D0),$P(^(0),U,3)=$P(^RTV(194.2,D0,0),U,15)" D ^DIC K DIC S DIC=DIE,X=+Y K:Y<0 X
 Q
 ;
9 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=9 D X9 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X9 S:X="" Y="@18"
 Q
10 S DW="0;11",DV="S",DU="",DLB="VOLUMES REQUESTED",DIFLD=11
 S DU="A:ALL VOLUMES;L:LATEST VOLUME;"
 S Y="LATEST VOLUME"
 G Y
X10 Q
11 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=11 D X11 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X11 S Y="@18"
 Q
12 S DQ=13 ;@15
13 S DW="0;4",DV="*P195.2'",DU="",DLB="RECORD TYPE RESTRICTION",DIFLD=4
 S DU="DIC(195.2,"
 S X=$P($P(RTTY,U),RTSEMI,2)
 S Y=X
 S X=Y,DB(DQ)=1 G:X="" N^DIE17:DV,A I $D(DE(DQ)),DV["I"!(DV["#") D E^DIE0 G A:'$D(X)
 G RD
X13 S DIC("S")="I $D(D0),$P(^(0),U,3)=$P(^RTV(194.2,D0,0),U,15)" D ^DIC K DIC S DIC=DIE,X=+Y K:Y<0 X
 Q
 ;
14 S DQ=15 ;@18
15 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=15 D X15 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X15 S:$D(RTQDT) Y="@20"
 Q
16 S DW="0;2",DV="RD",DU="",DLB="DATE RECORDS NEEDED",DIFLD=2
 S DE(DW)="C16^RTCP"
 G RE
C16 G C16S:$D(DE(16))[0 K DB
 S X=DE(16),DIC=DIE
 K ^RTV(194.2,"C",$E(X,1,30),DA)
C16S S X="" G:DG(DQ)=X C16F1 K DB
 S X=DG(DQ),DIC=DIE
 S ^RTV(194.2,"C",$E(X,1,30),DA)=""
C16F1 Q
X16 S %DT="ETX" D ^%DT S X=Y K:Y<1 X
 Q
 ;
17 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=17 D X17 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X17 S Y="@30"
 Q
18 S DQ=19 ;@20
19 D:$D(DG)>9 F^DIE17,DE S DQ=19,DW="0;2",DV="RD",DU="",DLB="DATE RECORDS NEEDED",DIFLD=2
 S DE(DW)="C19^RTCP"
 S X=$P(RTQDT,".")
 S Y=X
 S X=Y,DB(DQ)=1,DE(DW,"4/")="" G:X="" N^DIE17:DV,A I $D(DE(DQ)),DV["I"!(DV["#") D E^DIE0 G A:'$D(X)
 G RD:X="@",Z
C19 G C19S:$D(DE(19))[0 K DB
 S X=DE(19),DIC=DIE
 K ^RTV(194.2,"C",$E(X,1,30),DA)
C19S S X="" G:DG(DQ)=X C19F1 K DB
 S X=DG(DQ),DIC=DIE
 S ^RTV(194.2,"C",$E(X,1,30),DA)=""
C19F1 Q
X19 Q
20 S DQ=21 ;@30
21 D:$D(DG)>9 F^DIE17,DE S DQ=21,DW="0;3",DV="P200'",DU="",DLB="USER ENTERING REQUEST",DIFLD=3
 S DU="VA(200,"
 S X=RTDUZ
 S Y=X
 S X=Y,DB(DQ)=1,DE(DW,"4/")="" G:X="" N^DIE17:DV,A I $D(DE(DQ)),DV["I"!(DV["#") D E^DIE0 G A:'$D(X)
 G RD:X="@",Z
X21 Q
22 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=22 D X22 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X22 S:$D(RTB) Y="@40"
 Q
23 S DW="0;5",DV="R*P195.9X",DU="",DLB="BORROWER",DIFLD=5
 S DU="RTV(195.9,"
 G RE
X23 D PULL^RTDPA31 S DIC("S")="I $D(D0),$P(^RTV(194.2,D0,0),U,15)=$P(^RTV(195.9,Y,0),U,3) D DICS^RTDPA31" D ^DIC K DIC S DIC=DIE,X=+Y K:Y<0 X
 Q
 ;
24 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=24 D X24 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X24 S A=+$P(^RTV(194.2,DA,0),U,15) D INST1^RTUTL K A
 Q
25 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=25 D X25 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X25 S Y="@50"
 Q
26 S DQ=27 ;@40
27 S DW="0;5",DV="R*P195.9X",DU="",DLB="BORROWER",DIFLD=5
 S DU="RTV(195.9,"
 S X=RTB
 S Y=X
 S X=Y,DB(DQ)=1,DE(DW,"4/")="" G:X="" N^DIE17:DV,A I $D(DE(DQ)),DV["I"!(DV["#") D E^DIE0 G A:'$D(X)
 G RD:X="@",Z
X27 Q
28 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=28 D X28 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X28 S A=+$P(^RTV(194.2,DA,0),U,15) D INST1^RTUTL K A
 Q
29 S DQ=30 ;@50
30 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=30 D X30 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X30 S:'$D(RTINST) Y="@60"
 Q
31 S DW="0;12",DV="RP4'",DU="",DLB="INSTITUTION OF BORROWER",DIFLD=12
 S DU="DIC(4,"
 S X=RTINST
 S Y=X
 S X=Y,DB(DQ)=1,DE(DW,"4/")="" G:X="" N^DIE17:DV,A I $D(DE(DQ)),DV["I"!(DV["#") D E^DIE0 G A:'$D(X)
 G RD:X="@",Z
X31 Q
32 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=32 D X32 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X32 S Y="@70"
 Q
33 S DQ=34 ;@60
34 S DW="0;12",DV="RP4'",DU="",DLB="INSTITUTION OF BORROWER",DIFLD=12
 S DU="DIC(4,"
 G RE
X34 Q
35 S DQ=36 ;@70
36 S DW="0;10",DV="S",DU="",DLB="TYPE OF LIST",DIFLD=10
 S DU="1:SCHEDULING;2:ADHOC;3:RECORD RETIREMENT;"
 S X=$S($D(RTPLTY):RTPLTY,1:2)
 S Y=X
 S X=Y,DB(DQ)=1,DE(DW,"4/")="" G:X="" N^DIE17:DV,A I $D(DE(DQ)),DV["I"!(DV["#") D E^DIE0 G A:'$D(X)
 G RD:X="@",Z
X36 Q
37 S DW="0;6",DV="S",DU="",DLB="PULL LIST STATUS",DIFLD=6
 S DU="c:CHARGED;x:CANCELLED;r:REQUESTED;"
 S X="r"
 S Y=X
 S X=Y,DB(DQ)=1,DE(DW,"4/")="" G:X="" N^DIE17:DV,A I $D(DE(DQ)),DV["I"!(DV["#") D E^DIE0 G A:'$D(X)
 G RD:X="@",Z
X37 Q
38 S DW="0;7",DV="D",DU="",DLB="DATE/TIME CURRENT STATUS",DIFLD=7
 S X="NOW"
 S Y=X
 S X=Y,DB(DQ)=1 G:X="" N^DIE17:DV,A I $D(DE(DQ)),DV["I"!(DV["#") D E^DIE0 G A:'$D(X)
 G RD
X38 S %DT="TX" D ^%DT S X=Y K:Y<1 X
 Q
 ;
39 S DW="0;8",DV="P200'",DU="",DLB="USER RESPONSIBLE FOR STATUS",DIFLD=8
 S DU="VA(200,"
 S X=RTDUZ
 S Y=X
 S X=Y,DB(DQ)=1,DE(DW,"4/")="" G:X="" N^DIE17:DV,A I $D(DE(DQ)),DV["I"!(DV["#") D E^DIE0 G A:'$D(X)
 G RD:X="@",Z
X39 Q
40 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=40 D X40 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X40 K RTSEMI,RTDUZ
 Q
41 G 0^DIE17
