GMRAY18P ;SLC/DAN-CREATE NEW-STYLE XREF ;9:12 AM  7 Sep 2004
 ;;4.0;Adverse Reaction Tracking;**18**;Mar 29, 1996
 ;
 N GMRAXR,GMRARES,GMRAOUT
 S GMRAXR("FILE")=120.85315
 S GMRAXR("NAME")="AHDR"
 S GMRAXR("TYPE")="MU"
 S GMRAXR("USE")="A"
 S GMRAXR("EXECUTION")="F"
 S GMRAXR("ACTIVITY")=""
 S GMRAXR("SHORT DESCR")="Send data to HDR on entry/edit"
 S GMRAXR("DESCR",1)="Send data to HDR when the P&T addendum is added."
 S GMRAXR("SET")="Q:$D(DIU(0))  D SETOB^GMRAHDR"
 S GMRAXR("KILL")="Q:$D(DIU(0))  D KILLOB^GMRAHDR"
 S GMRAXR("WHOLE KILL")="Q"
 S GMRAXR("VAL",1)=.01
 S GMRAXR("VAL",1,"COLLATION")="F"
 D CREIXN^DDMOD(.GMRAXR,"k",.GMRARES,"GMRAOUT")
 Q
