GMRAY18A ;SLC/DAN-CREATE NEW-STYLE XREF ;9:06 AM  7 Sep 2004
 ;;4.0;Adverse Reaction Tracking;**18**;Mar 29, 1996
 ;
 N GMRAXR,GMRARES,GMRAOUT
 S GMRAXR("FILE")=120.8
 S GMRAXR("NAME")="AHDR"
 S GMRAXR("TYPE")="MU"
 S GMRAXR("USE")="A"
 S GMRAXR("EXECUTION")="R"
 S GMRAXR("ACTIVITY")=""
 S GMRAXR("SHORT DESCR")="Sends data to HDR upon entry"
 S GMRAXR("DESCR",1)="This cross reference will send the HDR allergy data upon entry or editing "
 S GMRAXR("DESCR",2)="of allergy related data."
 S GMRAXR("SET")="Q:$D(DIU(0))  D SETADR^GMRAHDR"
 S GMRAXR("KILL")="Q:$D(DIU(0))  D KILLADR^GMRAHDR"
 S GMRAXR("WHOLE KILL")="Q"
 S GMRAXR("VAL",1)=.01
 S GMRAXR("VAL",1,"COLLATION")="F"
 S GMRAXR("VAL",2)=.02
 S GMRAXR("VAL",2,"COLLATION")="F"
 S GMRAXR("VAL",3)=1
 S GMRAXR("VAL",3,"COLLATION")="F"
 S GMRAXR("VAL",4)=3.1
 S GMRAXR("VAL",4,"COLLATION")="F"
 S GMRAXR("VAL",5)=4
 S GMRAXR("VAL",5,"COLLATION")="F"
 S GMRAXR("VAL",6)=5
 S GMRAXR("VAL",6,"COLLATION")="F"
 S GMRAXR("VAL",7)=6
 S GMRAXR("VAL",7,"COLLATION")="F"
 S GMRAXR("VAL",8)=15
 S GMRAXR("VAL",8,"COLLATION")="F"
 S GMRAXR("VAL",9)=17
 S GMRAXR("VAL",9,"COLLATION")="F"
 S GMRAXR("VAL",10)=19
 S GMRAXR("VAL",10,"COLLATION")="F"
 S GMRAXR("VAL",11)=20
 S GMRAXR("VAL",11,"COLLATION")="F"
 S GMRAXR("VAL",12)=21
 S GMRAXR("VAL",12,"COLLATION")="F"
 S GMRAXR("VAL",13)=22
 S GMRAXR("VAL",13,"COLLATION")="F"
 S GMRAXR("VAL",14)=23
 S GMRAXR("VAL",14,"COLLATION")="F"
 S GMRAXR("VAL",15)=24
 S GMRAXR("VAL",15,"COLLATION")="F"
 D CREIXN^DDMOD(.GMRAXR,"k",.GMRARES,"GMRAOUT")
 Q
