GMRAY18K ;SLC/DAN-CREATE NEW-STYLE XREF ;9:10 AM  7 Sep 2004
 ;;4.0;Adverse Reaction Tracking;**18**;Mar 29, 1996
 ;
 N GMRAXR,GMRARES,GMRAOUT
 S GMRAXR("FILE")=120.8503
 S GMRAXR("NAME")="AHDR"
 S GMRAXR("TYPE")="MU"
 S GMRAXR("USE")="A"
 S GMRAXR("EXECUTION")="R"
 S GMRAXR("ACTIVITY")=""
 S GMRAXR("SHORT DESCR")="Send data to HDR"
 S GMRAXR("DESCR",1)="Send data to HDR when entries are added or edited in this multiple."
 S GMRAXR("SET")="Q:$D(DIU(0))  D SETOB^GMRAHDR"
 S GMRAXR("KILL")="Q:$D(DIU(0))  D KILLOB^GMRAHDR"
 S GMRAXR("WHOLE KILL")="Q"
 S GMRAXR("VAL",1)=.01
 S GMRAXR("VAL",1,"COLLATION")="F"
 S GMRAXR("VAL",2)=1
 S GMRAXR("VAL",2,"COLLATION")="F"
 S GMRAXR("VAL",3)=1.5
 S GMRAXR("VAL",3,"COLLATION")="F"
 S GMRAXR("VAL",4)=2
 S GMRAXR("VAL",4,"COLLATION")="F"
 S GMRAXR("VAL",5)=3
 S GMRAXR("VAL",5,"COLLATION")="F"
 S GMRAXR("VAL",6)=4
 S GMRAXR("VAL",6,"COLLATION")="F"
 S GMRAXR("VAL",7)=5
 S GMRAXR("VAL",7,"COLLATION")="F"
 S GMRAXR("VAL",8)=7
 S GMRAXR("VAL",8,"COLLATION")="F"
 S GMRAXR("VAL",9)=8
 S GMRAXR("VAL",9,"COLLATION")="F"
 S GMRAXR("VAL",10)=9
 S GMRAXR("VAL",10,"COLLATION")="F"
 S GMRAXR("VAL",11)=10
 S GMRAXR("VAL",11,"COLLATION")="F"
 S GMRAXR("VAL",12)=10.1
 S GMRAXR("VAL",12,"COLLATION")="F"
 S GMRAXR("VAL",13)=10.2
 S GMRAXR("VAL",13,"COLLATION")="F"
 S GMRAXR("VAL",14)=11
 S GMRAXR("VAL",14,"COLLATION")="F"
 S GMRAXR("VAL",15)=12
 S GMRAXR("VAL",15,"COLLATION")="F"
 S GMRAXR("VAL",16)=13
 S GMRAXR("VAL",16,"COLLATION")="F"
 S GMRAXR("VAL",17)=14
 S GMRAXR("VAL",17,"COLLATION")="F"
 S GMRAXR("VAL",18)=15
 S GMRAXR("VAL",18,"COLLATION")="F"
 S GMRAXR("VAL",19)=16
 S GMRAXR("VAL",19,"COLLATION")="F"
 S GMRAXR("VAL",20)=17
 S GMRAXR("VAL",20,"COLLATION")="F"
 D CREIXN^DDMOD(.GMRAXR,"k",.GMRARES,"GMRAOUT")
 Q
