GMRAY18L ;SLC/DAN-CREATE NEW-STYLE XREF ;9:11 AM  7 Sep 2004
 ;;4.0;Adverse Reaction Tracking;**18**;Mar 29, 1996
 ;
 N GMRAXR,GMRARES,GMRAOUT
 S GMRAXR("FILE")=120.8504
 S GMRAXR("NAME")="AHDR"
 S GMRAXR("TYPE")="MU"
 S GMRAXR("USE")="A"
 S GMRAXR("EXECUTION")="R"
 S GMRAXR("ACTIVITY")=""
 S GMRAXR("SHORT DESCR")="Send data to HDR"
 S GMRAXR("DESCR",1)="Send data to HDR when entries are added or edited in this multiple"
 S GMRAXR("SET")="Q:$D(DIU(0))  D SETOB^GMRAHDR"
 S GMRAXR("KILL")="Q:$D(DIU(0))  D KILLOB^GMRAHDR"
 S GMRAXR("WHOLE KILL")="Q"
 S GMRAXR("VAL",1)=.01
 S GMRAXR("VAL",1,"COLLATION")="F"
 S GMRAXR("VAL",2)=1
 S GMRAXR("VAL",2,"COLLATION")="F"
 S GMRAXR("VAL",3)=2
 S GMRAXR("VAL",3,"COLLATION")="F"
 D CREIXN^DDMOD(.GMRAXR,"k",.GMRARES,"GMRAOUT")
 Q
