GMRAY18F ;SLC/DAN-CREATE NEW-STYLE XREF ;12/20/04  15:59
 ;;4.0;Adverse Reaction Tracking;**18**;Mar 29, 1996
 ;
 N GMRAXR,GMRARES,GMRAOUT
 S GMRAXR("FILE")=120.813
 S GMRAXR("NAME")="AHDR"
 S GMRAXR("TYPE")="MU"
 S GMRAXR("USE")="A"
 S GMRAXR("EXECUTION")="R"
 S GMRAXR("ACTIVITY")=""
 S GMRAXR("SHORT DESCR")="Send HDR data upon entry or edit"
 S GMRAXR("DESCR",1)="Send HDR updated information when the chart is marked."
 S GMRAXR("SET")="Q:$D(DIU(0))  D SETADR^GMRAHDR"
 S GMRAXR("KILL")="Q:$D(DIU(0))  D KILLADR^GMRAHDR"
 S GMRAXR("WHOLE KILL")="Q"
 S GMRAXR("VAL",1)=.01
 S GMRAXR("VAL",1,"COLLATION")="F"
 S GMRAXR("VAL",2)=1
 S GMRAXR("VAL",2,"COLLATION")="F"
 D CREIXN^DDMOD(.GMRAXR,"k",.GMRARES,"GMRAOUT")
 Q
