GMRAY18E ;SLC/DAN-CREATE NEW-STYLE XREF ;9:08 AM  7 Sep 2004
 ;;4.0;Adverse Reaction Tracking;**18**;Mar 29, 1996
 ;
 N GMRAXR,GMRARES,GMRAOUT
 S GMRAXR("FILE")=120.826
 S GMRAXR("NAME")="AHDR"
 S GMRAXR("TYPE")="MU"
 S GMRAXR("USE")="A"
 S GMRAXR("EXECUTION")="R"
 S GMRAXR("ACTIVITY")=""
 S GMRAXR("SHORT DESCR")="Sends data to HDR upon entry or edit"
 S GMRAXR("DESCR",1)="Sends data to the HDR when comments are added or updated."
 S GMRAXR("SET")="Q:$D(DIU(0))  D SETADR^GMRAHDR"
 S GMRAXR("KILL")="Q:$D(DIU(0))  D KILLADR^GMRAHDR"
 S GMRAXR("WHOLE KILL")="Q"
 S GMRAXR("VAL",1)=.01
 S GMRAXR("VAL",1,"COLLATION")="F"
 S GMRAXR("VAL",2)=1
 S GMRAXR("VAL",2,"COLLATION")="F"
 S GMRAXR("VAL",3)=1.5
 S GMRAXR("VAL",3,"COLLATION")="F"
 D CREIXN^DDMOD(.GMRAXR,"k",.GMRARES,"GMRAOUT")
 Q
