DGJXE1 ; ;09/19/10
 D DE G BEGIN
DE S DIE="^VAS(393,",DIC=DIE,DP=393,DL=1,DIEL=0,DU="" K DG,DE,DB Q:$O(^VAS(393,DA,""))=""
 I $D(^("DT")) S %Z=^("DT") S %=$P(%Z,U,1) S:%]"" DE(1)=% S %=$P(%Z,U,2) S:%]"" DE(6)=% S %=$P(%Z,U,3) S:%]"" DE(10)=% S %=$P(%Z,U,4) S:%]"" DE(14)=% S %=$P(%Z,U,5) S:%]"" DE(18)=% S %=$P(%Z,U,6) S:%]"" DE(22)=% S %=$P(%Z,U,7) S:%]"" DE(27)=%
 I  S %=$P(%Z,U,8) S:%]"" DE(31)=%
 K %Z Q
 ;
W W !?DL+DL-2,DLB_": "
 Q
O D W W Y W:$X>45 !?9
 I $L(Y)>19,'DV,DV'["I",(DV["F"!(DV["K")) G RW^DIR2
 W:Y]"" "// " I 'DV,DV["I",$D(DE(DQ))#2 S X="" W "  (No Editing)" Q
TR R X:DTIME E  S (DTOUT,X)=U W $C(7)
 Q
A K DQ(DQ) S DQ=DQ+1
B G @DQ
RE G PR:$D(DE(DQ)) D W,TR
N I X="" G NKEY:$D(^DD("KEY","F",DP,DIFLD)),A:DV'["R",X:'DV,X:D'>0,A
RD G QS:X?."?" I X["^" D D G ^DIE17
 I X="@" D D G Z^DIE2
 I X=" ",DV["d",DV'["P",$D(^DISV(DUZ,"DIE",DLB)) S X=^(DLB) I DV'["D",DV'["S" W "  "_X
T G M^DIE17:DV,^DIE3:DV["V",P:DV'["S" X:$D(^DD(DP,DIFLD,12.1)) ^(12.1) I X?.ANP D SET I 'DDER X:$D(DIC("S")) DIC("S") I  W:'$D(DB(DQ)) "  "_% G V
 K DDER G X
P I DV["P" S DIC=U_DU,DIC(0)=$E("EN",$D(DB(DQ))+1)_"M"_$E("L",DV'["'") S:DIC(0)["L" DLAYGO=+$P(DV,"P",2) G:DV["*" AST^DIED D NOSCR^DIED S X=+Y,DIC=DIE G X:X<0
 G V:DV'["N" D D I $L($P(X,"."))>24 K X G Z
 I $P(DQ(DQ),U,5)'["$",X?.1"-".N.1".".N,$P(DQ(DQ),U,5,99)["+X'=X" S X=+X
V D @("X"_DQ) K YS
Z K DIC("S"),DLAYGO I $D(X),X'=U D:$G(DE(DW,"INDEX")) SAVEVALS G:'$$KEYCHK UNIQFERR^DIE17 S DG(DW)=X S:DV["d" ^DISV(DUZ,"DIE",DLB)=X G A
X W:'$D(ZTQUEUED) $C(7),"??" I $D(DB(DQ)) G Z^DIE17
 S X="?BAD"
QS S DZ=X D D,QQ^DIEQ G B
D S D=DIFLD,DQ(DQ)=DLB_U_DV_U_DU_U_DW_U_$P($T(@("X"_DQ))," ",2,99) Q
Y I '$D(DE(DQ)) D O G RD:"@"'[X,A:DV'["R"&(X="@"),X:X="@" S X=Y G N
PR S DG=DV,Y=DE(DQ),X=DU I $D(DQ(DQ,2)) X DQ(DQ,2) G RP
R I DG["P",@("$D(^"_X_"0))") S X=+$P(^(0),U,2) G RP:'$D(^(Y,0)) S Y=$P(^(0),U),X=$P(^DD(X,.01,0),U,3),DG=$P(^(0),U,2) G R
 I DG["V",+Y,$P(Y,";",2)["(",$D(@(U_$P(Y,";",2)_"0)")) S X=+$P(^(0),U,2) G RP:'$D(^(+Y,0)) S Y=$P(^(0),U) I $D(^DD(+X,.01,0)) S DG=$P(^(0),U,2),X=$P(^(0),U,3) G R
 X:DG["D" ^DD("DD") I DG["S" S %=$P($P(";"_X,";"_Y_":",2),";") S:%]"" Y=%
RP D O I X="" S X=DE(DQ) G A:'DV,A:DC<2,N^DIE17
I I DV'["I",DV'["#" G RD
 D E^DIE0 G RD:$D(X),PR
 Q
SET N DIR S DIR(0)="SV"_$E("o",$D(DB(DQ)))_U_DU,DIR("V")=1
 I $D(DB(DQ)),'$D(DIQUIET) N DIQUIET S DIQUIET=1
 D ^DIR I 'DDER S %=Y(0),X=Y
 Q
SAVEVALS S @DIEZTMP@("V",DP,DIIENS,DIFLD,"O")=$G(DE(DQ)) S:$D(^("F"))[0 ^("F")=$G(DE(DQ))
 I $D(DE(DW,"4/")) S @DIEZTMP@("V",DP,DIIENS,DIFLD,"4/")=""
 E  K @DIEZTMP@("V",DP,DIIENS,DIFLD,"4/")
 Q
NKEY W:'$D(ZTQUEUED) "??  Required key field" S X="?BAD" G QS
KEYCHK() Q:$G(DE(DW,"KEY"))="" 1 Q @DE(DW,"KEY")
BEGIN S DNM="DGJXE1",DQ=1
1 D:$D(DG)>9 F^DIE17,DE S DQ=1,DW="DT;1",DV="DX",DU="",DLB="DATE DICTATED",DIFLD=10.01
 S DE(DW)="C1^DGJXE1"
 G RE
C1 G C1S:$D(DE(1))[0 K DB
 S X=DE(1),DIC=DIE
 S DGJFDIC=1 D PHYDEF^DGJTUTL
C1S S X="" G:DG(DQ)=X C1F1 K DB
 S X=DG(DQ),DIC=DIE
 S DGJFDIC=1 D PHYDEF^DGJTUTL
C1F1 Q
X1 S %DT(0)="-NOW",%DT="ETX" D ^%DT K %DT(0) S X=Y K:Y<1 X
 Q
 ;
2 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=2 D X2 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X2 I X="" S $P(^VAS(393,D0,"DT"),"^",2)="",$P(^("DT"),"^",3)="",$P(^("DT"),"^",4)="",$P(^("DT"),"^",5)="",$P(^("DT"),"^",6)="",$P(^("DT"),"^",7)="",$P(^("DT"),"^",8)=""
 Q
3 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=3 D X3 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X3 I X="" S DGJTST="INCOMPLETE",Y="@2"
 Q
4 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=4 D X4 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X4 S DGJTDDT=$S($P(^VAS(393,D0,0),"^",4)]"":$P(^DGPM($P(^VAS(393,D0,0),"^",4),0),"^",1),1:$P(^VAS(393,D0,0),"^",3))
 Q
5 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=5 D X5 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X5 S DGJTDDT=$S(DGJTDDT[".":$P(DGJTDDT,".",1),1:DGJTDDT) I X<DGJTDDT S $P(^VAS(393,D0,"DT"),"^",1)="" W !,"Date must be equal to or after EVENT DATE... no time required." S Y="@6"
 Q
6 D:$D(DG)>9 F^DIE17,DE S DQ=6,DW="DT;2",DV="P200'",DU="",DLB="DICTATED BY",DIFLD=10.02
 S DE(DW)="C6^DGJXE1"
 S DU="VA(200,"
 G RE
C6 G C6S:$D(DE(6))[0 K DB
 S X=DE(6),DIC=DIE
 S DGJFDIC=1 D PHYDEF^DGJTUTL
C6S S X="" G:DG(DQ)=X C6F1 K DB
 S X=DG(DQ),DIC=DIE
 S DGJFDIC=1 D PHYDEF^DGJTUTL
C6F1 Q
X6 Q
7 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=7 D X7 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X7 I X="" S $P(^VAS(393,D0,"DT"),"^",1)="",$P(^("DT"),"^",3)="",$P(^("DT"),"^",4)="",$P(^("DT"),"^",5)="",$P(^("DT"),"^",6)="",$P(^("DT"),"^",7)="",$P(^("DT"),"^",8)="" S DGJTST="INCOMPLETE",Y="@2"
 Q
8 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=8 D X8 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X8 S DGJTST="DICTATED"
 Q
9 S DQ=10 ;@9
10 D:$D(DG)>9 F^DIE17,DE S DQ=10,DW="DT;3",DV="DX",DU="",DLB="DATE TRANSCRIBED",DIFLD=10.03
 S DE(DW)="C10^DGJXE1"
 G RE
C10 G C10S:$D(DE(10))[0 K DB
 S X=DE(10),DIC=DIE
 S DGJFSIG=1 D PHYDEF^DGJTUTL
C10S S X="" G:DG(DQ)=X C10F1 K DB
 S X=DG(DQ),DIC=DIE
 S DGJFSIG=1 D PHYDEF^DGJTUTL
C10F1 Q
X10 S %DT(0)="-NOW",%DT="ETX" D ^%DT K %DT(0) S X=Y K:Y<1 X
 Q
 ;
11 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=11 D X11 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X11 I X="" S $P(^VAS(393,D0,"DT"),"^",4)=""
 Q
12 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=12 D X12 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X12 I X]"",X<$P(^VAS(393,D0,"DT"),"^",1) W !!?5,"Date must be after the DATE DICTATED" S $P(^VAS(393,D0,"DT"),"^",3)="" S Y="@9"
 Q
13 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=13 D X13 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X13 I X="" S DGJTST="DICTATED",Y="@2"
 Q
14 D:$D(DG)>9 F^DIE17,DE S DQ=14,DW="DT;4",DV="V",DU="",DLB="TRANSCRIBED BY",DIFLD=10.04
 S DE(DW)="C14^DGJXE1"
 G RE
C14 G C14S:$D(DE(14))[0 K DB
 S X=DE(14),DIC=DIE
 S DGJFSIG=1 D PHYDEF^DGJTUTL
C14S S X="" G:DG(DQ)=X C14F1 K DB
 S X=DG(DQ),DIC=DIE
 S DGJFSIG=1 D PHYDEF^DGJTUTL
C14F1 Q
X14 Q
15 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=15 D X15 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X15 I X="" S $P(^VAS(393,D0,"DT"),"^",3)="",DGJTST="DICTATED",Y="@2"
 Q
16 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=16 D X16 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X16 S DGJTST="TRANSCRIBED"
 Q
17 S DQ=18 ;@10
18 D:$D(DG)>9 F^DIE17,DE S DQ=18,DW="DT;5",DV="DX",DU="",DLB="DATE SIGNED",DIFLD=10.05
 S DE(DW)="C18^DGJXE1"
 G RE
C18 G C18S:$D(DE(18))[0 K DB
 S X=DE(18),DIC=DIE
 S DGJFREV=1 D PHYDEF^DGJTUTL
C18S S X="" G:DG(DQ)=X C18F1 K DB
 S X=DG(DQ),DIC=DIE
 S DGJFREV=1 D PHYDEF^DGJTUTL
C18F1 Q
X18 S %DT(0)="-NOW",%DT="ETX" D ^%DT K %DT(0) S X=Y K:Y<1 X
 Q
 ;
19 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=19 D X19 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X19 I X="" S $P(^VAS(393,D0,"DT"),"^",6)=""
 Q
20 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=20 D X20 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X20 I X]"",X<$P(^VAS(393,D0,"DT"),"^",1) W !!?5,"Date must be after the DATE DICTATED" S $P(^VAS(393,D0,"DT"),"^",5)="",Y="@10"
 Q
21 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=21 D X21 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X21 I X="" S DGJTST="TRANSCRIBED",Y="@2"
 Q
22 D:$D(DG)>9 F^DIE17,DE S DQ=22,DW="DT;6",DV="P200'",DU="",DLB="SIGNED BY",DIFLD=10.06
 S DE(DW)="C22^DGJXE1"
 S DU="VA(200,"
 G RE
C22 G C22S:$D(DE(22))[0 K DB
 S X=DE(22),DIC=DIE
 S DGJFREV=1 D PHYDEF^DGJTUTL
C22S S X="" G:DG(DQ)=X C22F1 K DB
 S X=DG(DQ),DIC=DIE
 S DGJFREV=1 D PHYDEF^DGJTUTL
C22F1 Q
X22 Q
23 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=23 D X23 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X23 I X="" S $P(^VAS(393,D0,"DT"),"^",5)="",DGJTST="TRANSCRIBED",Y="@2"
 Q
24 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=24 D X24 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X24 S DGJTST="SIGNED"
 Q
25 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=25 D X25 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X25 I $P(DGJTDEL,"^",3)=0 S DGJTST="SIGNED NO REVIEW",Y="@2"
 Q
26 S DQ=27 ;@11
27 D:$D(DG)>9 F^DIE17,DE S DQ=27,DW="DT;7",DV="DX",DU="",DLB="DATE REVIEWED",DIFLD=10.07
 S DE(DW)="C27^DGJXE1"
 G RE
C27 G C27S:$D(DE(27))[0 K DB
 S X=DE(27),DIC=DIE
 S DGJREVD=1 D PHYDEF^DGJTUTL
C27S S X="" G:DG(DQ)=X C27F1 K DB
 S X=DG(DQ),DIC=DIE
 S DGJREVD=1 D PHYDEF^DGJTUTL
C27F1 Q
X27 S %DT(0)="-NOW",%DT="ETX" D ^%DT K %DT(0) S X=Y K:Y<1 X
 Q
 ;
28 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=28 D X28 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X28 I X="" S $P(^VAS(393,D0,"DT"),"^",8)=""
 Q
29 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=29 D X29 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X29 I X]"",X<$P(^VAS(393,D0,"DT"),"^",1) W !!?5,"Date must be after the DATE DICTATED" S $P(^VAS(393,D0,"DT"),"^",7)="",Y="@11"
 Q
30 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=30 D X30 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X30 I X="" S DGJTST="SIGNED",Y="@2"
 Q
31 D:$D(DG)>9 F^DIE17,DE S DQ=31,DW="DT;8",DV="P200'",DU="",DLB="REVIEWED BY",DIFLD=10.08
 S DE(DW)="C31^DGJXE1"
 S DU="VA(200,"
 G RE
C31 G C31S:$D(DE(31))[0 K DB
 D ^DGJXE2
C31S S X="" G:DG(DQ)=X C31F1 K DB
 D ^DGJXE3
C31F1 Q
X31 Q
32 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=32 D X32 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X32 I X="" S $P(^VAS(393,D0,"DT"),"^",7)="",DGJTST="SIGNED",Y="@2"
 Q
33 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=33 D X33 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X33 S DGJTST="REVIEWED"
 Q
34 S DQ=35 ;@2
35 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=35 D X35 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X35 I X="" S DGJTUP=1
 Q
36 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=36 D X36 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X36 I X]"" S DGJTUP=1
 Q
37 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=37 D X37 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X37 S DGJTST=^VAS(393,D0,"DT")
 Q
38 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=38 D X38 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X38 I $P(DGJTST,"^",1)']"" S DGJTST="INCOMPLETE" S Y="@8"
 Q
39 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=39 D X39 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X39 I $P(DGJTST,"^",3)']"" S DGJTST="DICTATED" S Y="@8"
 Q
40 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=40 D X40 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X40 I $P(DGJTST,"^",5)']"" S DGJTST="TRANSCRIBED" S Y="@8"
 Q
41 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=41 D X41 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X41 I $P(DGJTST,"^",7)']"" S DGJTST="SIGNED" S Y="@8"
 Q
42 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=42 D X42 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X42 I $P(DGJTDEL,"^",3)=0 S DGJTST="SIGNED NO REVIEW"
 Q
43 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=43 D X43 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X43 I $P(DGJTDEL,"^",3)=1 S DGJTST="REVIEWED"
 Q
44 S DQ=45 ;@8
45 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=45 D X45 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X45 S DGJTST=$O(^DG(393.2,"B",DGJTST,0))
 Q
46 D:$D(DG)>9 F^DIE17 G ^DGJXE4
