DGPMX62 ; ;11/06/06
 S X=DG(DQ),DIC=DIE
 S DGPMDDF=9 D ^DGPMDD1
 S X=DG(DQ),DIC=DIE
 S DGPMDDF=9,DGPMDDT=1 D ^DGPMDDCN
 S X=DG(DQ),DIC=DIE
 I $D(^DGPM(+$P(^DGPM(DA,0),"^",24),0)),($P(^(0),"^",2)=1) S A1B2TAG="ADM1" D ^A1B2XFR
 S X=DG(DQ),DIC=DIE
 S Y=^DGPM(DA,0) I +Y,Y<DT S Y=$P(Y,U,2) I Y=6,X'=$P(Y,U,9) S DGHNYT=13 D ^DGPMGLC
 S X=DG(DQ),DIC=DIE
 D:($T(ADGRU^DGRUDD01)'="") ADGRU^DGRUDD01(DFN)
 I $D(DE(14))'[0!(^DD(DP,DIFLD,"AUDIT")'="e") S X=DG(DQ),DIIX=3_U_DIFLD D AUDIT^DIET
