DGPTX14 ; ;09/19/10
 S X=DE(17),DIC=DIE
 ;
 S X=DE(17),DIC=DIE
 ;
 S X=DE(17),DIC=DIE
 ;
 S X=DE(17),DIC=DIE
 D AUTOUPD^DGENA2(DA)
 S X=DE(17),DIC=DIE
 X "S DFN=DA D EN^DGMTR K DGREQF"
 S X=DE(17),DIC=DIE
 D EVENT^IVMPLOG(DA)
