VEPEREM2 ; RSL/DAOU - Computed findings for DOQIT extracts. ; 22 Jun 2005  9:10 AM
 ;;2.0;CLINICAL REMINDERS;;Feb 04, 2005
 ;
 ;==========================================================
PC1(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.61 D PATREG^VEPEREX
 Q
 ;
PC5(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.65 D PATREG^VEPEREX
 Q
 ;
PC6(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.66 D PATREG^VEPEREX
 Q
 ;
PC7(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.67 D PATREG^VEPEREX
 Q
 ;
PC8(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.68 D PATREG^VEPEREX
 Q
 ;
PC9(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.69 D PATREG^VEPEREX
 Q
 ;
PC10(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.7 D PATREG^VEPEREX
 Q
 ;
PC11(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.71 D PATREG^VEPEREX
 Q
 ;
PC12(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.72 D PATREG^VEPEREX
 Q
 ;
DM1(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.31 D PATREG^VEPEREX
 Q
 ;
DM2(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.32 D PATREG^VEPEREX
 Q
 ;
DM3(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.33 D PATREG^VEPEREX
 Q
 ;
DM4(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.34 D PATREG^VEPEREX
 Q
 ;
DM5(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.35 D PATREG^VEPEREX
 Q
 ;
DM6(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.36 D PATREG^VEPEREX
 Q
 ;
DM7(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.37 D PATREG^VEPEREX
 Q
 ;
DM8(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.38 D PATREG^VEPEREX
 Q
 ;
