VEPEREM1 ; MRM/DAOU - Computed findings for DOQIT extracts. ; 6/21/05 11:59am
 ;;2.0;CLINICAL REMINDERS;;Feb 04, 2005
 ;
 ;==========================================================
 ;This routine contains the computed findings for DOQ-IT reminders
 ;
CAD1(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.21 D PATREG^VEPEREX
 Q
CAD2(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.22 D PATREG^VEPEREX
 Q
CAD3(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.23 D PATREG^VEPEREX
 Q
CAD4(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.24 D PATREG^VEPEREX
 Q
CAD5(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.25 D PATREG^VEPEREX
 Q
CAD6(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.26 D PATREG^VEPEREX
 Q
CAD7(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.27 D PATREG^VEPEREX
 Q
HF1(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.51 D PATREG^VEPEREX
 Q
HF2(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.52 D PATREG^VEPEREX
 Q
HF3(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.53 D PATREG^VEPEREX
 Q
HF4(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.54 D PATREG^VEPEREX
 Q
HF5(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.55 D PATREG^VEPEREX
 Q
HF6(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.56 D PATREG^VEPEREX
 Q
HF7(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.57 D PATREG^VEPEREX
 Q
HF8(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.58 D PATREG^VEPEREX
 Q
HTN1(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.41 D PATREG^VEPEREX
 Q
HTN2(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.42 D PATREG^VEPEREX
 Q
HTN3(DFN,TEST,DATE,DATA,TEXT) ;
 N FIELD
 S FIELD=.43 D PATREG^VEPEREX
 Q
