ZVEMSGH ;DJB,VSHL**VShell Global - Help Text ; 8/29/02 9:21pm
 ;;12;VPE;;COPYRIGHT David Bolduc @1993
 ;
 Q
TEXT ;Load HELP and other text
 NEW CNT,LN,RTN,TAG,TXT
 KILL ^%ZVEMS("ZZ") S ^%ZVEMS("ZZ")="Help Text"
 S RTN="ZVEMSH1",TAG="INTRO" D TEXT1
 S RTN="ZVEMSH2",TAG="KEYS" D TEXT1
 S RTN="ZVEMSH3" F TAG="QWIK","USER" D TEXT1
 S RTN="ZVEMSH4",TAG="SYSTEM" D TEXT1
 S RTN="ZVEMSH5" F TAG="BOXES","VENDOR" D TEXT1
 S RTN="ZVEMSH6" F TAG="CLH","PGM" D TEXT1
 S RTN="ZVEMSH7" F TAG="PARAM","PROT" D TEXT1
 S RTN="ZVEMSH8",TAG="MISC" D TEXT1
 S RTN="ZVEMSH9",TAG="KERN" D TEXT1
 S RTN="ZVEMSF1" F TAG="DDS","DIAC","DIB","DIM","DIO2" D TEXT1
 S RTN="ZVEMSF2",TAG="DIC" D TEXT1
 S RTN="ZVEMSF3" F TAG="DIC1","DICN" D TEXT1
 S RTN="ZVEMSF4" F TAG="DICQ","DICRW","DID","DIEZ","DIFG","DICD","DIKZ" D TEXT1
 S RTN="ZVEMSF5",TAG="DIE" D TEXT1
 S RTN="ZVEMSF6" F TAG="DIK","DIPZ","DIR","DIS" D TEXT1
 S RTN="ZVEMSF7" F TAG="DIP","DIPT" D TEXT1
 S RTN="ZVEMSF8" F TAG="DIQ","DIQ1" D TEXT1
 S RTN="ZVEMSF9",TAG="DIWF" D TEXT1
 S RTN="ZVEMSFA" F TAG="DIU2","DIWE","DIWP","DIWW" D TEXT1
 S RTN="ZVEMSFB" F TAG="%DT","COMMA" D TEXT1
 S RTN="ZVEMSFC",TAG="%DTC" D TEXT1
 S RTN="ZVEMSFD" F TAG="%RCR","DDIOL","DIAXU" D TEXT1
 S RTN="ZVEMSLA",TAG="DATE" D TEXT1
 S RTN="ZVEMSLB",TAG="STRING" D TEXT1
 S RTN="ZVEMSLC",TAG="MATH" D TEXT1
 S RTN="ZVEMSLD",TAG="MEAS" D TEXT1
 S RTN="ZVEMSN",TAG="NOTES" D TEXT1
 S CNT=1
 S RTN="ZVEMDH1",TAG="VEDD1" D TEXT2
 S RTN="ZVEMDH2",TAG="VEDD1" D TEXT2
 S RTN="ZVEMDH3",TAG="VEDD1" D TEXT2
 S RTN="ZVEMDH4",TAG="VEDD2" D TEXT2
 S RTN="ZVEMDH5",TAG="VEDD2" D TEXT2
 S RTN="ZVEMGH",TAG="VGL1" D TEXT1
 S CNT=1
 S RTN="ZVEMGH1",TAG="VGL2" D TEXT2
 S RTN="ZVEMGH2",TAG="VGL2" D TEXT2
 S CNT=1
 S RTN="ZVEMRH",TAG="VRR1" D TEXT2
 S RTN="ZVEMRH1",TAG="VRR1" D TEXT2
 S RTN="ZVEMRHK",TAG="VRR2" D TEXT2
 S RTN="ZVEMRHL",TAG="LIBRARY" D TEXT2
 S RTN="ZVEMRHW",TAG="WEB" D TEXT2
 Q
TEXT1 ;Move text to ^%ZVEMS("ZZ")
 S CNT=1 W "."
 ;
TEXT2 ;
 X "F LN=1:1 S TXT=$T("_TAG_"+LN^"_RTN_") Q:TXT']""""  S TXT=$P(TXT,"";;;"",2,999) Q:TXT=""***""  S ^%ZVEMS(""ZZ"",TAG,CNT)=TXT,CNT=CNT+1"
 Q
