DVBAXA ; GENERATED FROM 'DVBA C ADD 2507 PAT' INPUT TEMPLATE(#965), FILE 2;06/08/01
 D DE G BEGIN
DE S DIE="^DPT(",DIC=DIE,DP=2,DL=1,DIEL=0,DU="" K DG,DE,DB Q:$O(^DPT(DA,""))=""
 I $D(^(0)) S %Z=^(0) S %=$P(%Z,U,1) S:%]"" DE(4)=% S %=$P(%Z,U,2) S:%]"" DE(5)=% S %=$P(%Z,U,9) S:%]"" DE(6)=%
 I $D(^(.3)) S %Z=^(.3) S %=$P(%Z,U,1) S:%]"" DE(9)=% S %=$P(%Z,U,2) S:%]"" DE(10)=%
 I $D(^(.31)) S %Z=^(.31) S %=$P(%Z,U,3) S:%]"" DE(7)=% S %=$P(%Z,U,4) S:%]"" DE(8)=%
 K %Z Q
 ;
W W !?DL+DL-2,DLB_": "
 Q
O D W W Y W:$X>45 !?9
 I $L(Y)>19,'DV,DV'["I",(DV["F"!(DV["K")) G RW^DIR2
 W:Y]"" "// " I 'DV,DV["I",$D(DE(DQ))#2 S X="" W "  (No Editing)" Q
TR R X:DTIME E  S (DTOUT,X)=U W $C(7)
 Q
A K DQ(DQ) S DQ=DQ+1
B G @DQ
RE G PR:$D(DE(DQ)) D W,TR
N I X="" G NKEY:$D(^DD("KEY","F",DP,DIFLD)),A:DV'["R",X:'DV,X:D'>0,A
RD G QS:X?."?" I X["^" D D G ^DIE17
 I X="@" D D G Z^DIE2
 I X=" ",DV["d",DV'["P",$D(^DISV(DUZ,"DIE",DLB)) S X=^(DLB) I DV'["D",DV'["S" W "  "_X
T G M^DIE17:DV,^DIE3:DV["V",P:DV'["S" X:$D(^DD(DP,DIFLD,12.1)) ^(12.1) I X?.ANP D SET I 'DDER X:$D(DIC("S")) DIC("S") I  W:'$D(DB(DQ)) "  "_% G V
 K DDER G X
P I DV["P" S DIC=U_DU,DIC(0)=$E("EN",$D(DB(DQ))+1)_"M"_$E("L",DV'["'") S:DIC(0)["L" DLAYGO=+$P(DV,"P",2) G:DV["*" AST^DIED D NOSCR^DIED S X=+Y,DIC=DIE G X:X<0
 G V:DV'["N" D D I $L($P(X,"."))>24 K X G Z
 I $P(DQ(DQ),U,5)'["$",X?.1"-".N.1".".N,$P(DQ(DQ),U,5,99)["+X'=X" S X=+X
V D @("X"_DQ) K YS
Z K DIC("S"),DLAYGO I $D(X),X'=U D:$G(DE(DW,"INDEX")) SAVEVALS G:'$$KEYCHK UNIQFERR^DIE17 S DG(DW)=X S:DV["d" ^DISV(DUZ,"DIE",DLB)=X G A
X W:'$D(ZTQUEUED) $C(7),"??" I $D(DB(DQ)) G Z^DIE17
 S X="?BAD"
QS S DZ=X D D,QQ^DIEQ G B
D S D=DIFLD,DQ(DQ)=DLB_U_DV_U_DU_U_DW_U_$P($T(@("X"_DQ))," ",2,99) Q
Y I '$D(DE(DQ)) D O G RD:"@"'[X,A:DV'["R"&(X="@"),X:X="@" S X=Y G N
PR S DG=DV,Y=DE(DQ),X=DU I $D(DQ(DQ,2)) X DQ(DQ,2) G RP
R I DG["P",@("$D(^"_X_"0))") S X=+$P(^(0),U,2) G RP:'$D(^(Y,0)) S Y=$P(^(0),U),X=$P(^DD(X,.01,0),U,3),DG=$P(^(0),U,2) G R
 I DG["V",+Y,$P(Y,";",2)["(",$D(@(U_$P(Y,";",2)_"0)")) S X=+$P(^(0),U,2) G RP:'$D(^(+Y,0)) S Y=$P(^(0),U) I $D(^DD(+X,.01,0)) S DG=$P(^(0),U,2),X=$P(^(0),U,3) G R
 X:DG["D" ^DD("DD") I DG["S" S %=$P($P(";"_X,";"_Y_":",2),";") S:%]"" Y=%
RP D O I X="" S X=DE(DQ) G A:'DV,A:DC<2,N^DIE17
I I DV'["I",DV'["#" G RD
 D E^DIE0 G RD:$D(X),PR
 Q
SET N DIR S DIR(0)="SV"_$E("o",$D(DB(DQ)))_U_DU,DIR("V")=1
 I $D(DB(DQ)),'$D(DIQUIET) N DIQUIET S DIQUIET=1
 D ^DIR I 'DDER S %=Y(0),X=Y
 Q
SAVEVALS S @DIEZTMP@("V",DP,DIIENS,DIFLD,"O")=$G(DE(DQ)) S:$D(^("F"))[0 ^("F")=$G(DE(DQ))
 I $D(DE(DW,"4/")) S @DIEZTMP@("V",DP,DIIENS,DIFLD,"4/")=""
 E  K @DIEZTMP@("V",DP,DIIENS,DIFLD,"4/")
 Q
NKEY W:'$D(ZTQUEUED) "??  Required key field" S X="?BAD" G QS
KEYCHK() Q:$G(DE(DW,"KEY"))="" 1 Q @DE(DW,"KEY")
BEGIN S DNM="DVBAXA",DQ=1
 N DIEZTMP,DIEZAR,DIEZRXR,DIIENS,DIXR K DIEFIRE,DIEBADK S DIEZTMP=$$GETTMP^DIKC1("DIEZ")
 M DIEZAR=^DIE(965,"AR") S DICRREC="TRIG^DIE17"
 S:$D(DTIME)[0 DTIME=300 S D0=DA,DIIENS=DA_",",DIEZ=965,U="^"
1 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=1 D X1 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X1 S DVBACPLT=0 I '$D(IOF) S IOP="HOME" D ^%ZIS K IOP
 Q
2 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=2 D X2 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X2 W @IOF,!,"Please review previous information entered as well as",!,"entering additional REQUIRED information:",!!!
 Q
3 S DQ=4 ;@1
4 S DW="0;1",DV="RFX",DU="",DLB="NAME",DIFLD=.01
 S DE(DW)="C4^DVBAXA",DE(DW,"INDEX")=1
 G RE
C4 G C4S:$D(DE(4))[0 K DB
 S X=DE(4),DIC=DIE
 K ^DPT("B",$E(X,1,30),DA)
 S X=DE(4),DIC=DIE
 X "Q:$P(^DPT(DA,0),U,9)']""""  K ^DPT(""BS5"",$E(X,1)_$E($P(^(0),U,9),6,9),DA)"
 S X=DE(4),DIC=DIE
 D EVENT^IVMPLOG(DA)
 S X=DE(4),DIC=DIE
 S A1B2TAG="PAT" D ^A1B2XFR
 S X=DE(4),DIC=DIE
 X "S DFN=DA D ^DGPATN K DGNEWVAL Q"
 S X=DE(4),DIC=DIE
 S IVMX=X,X="IVMPXFR" X ^%ZOSF("TEST") D:$T DPT^IVMPXFR S X=IVMX K IVMX
 S X=DE(4),DIC=DIE
 I ($T(AVAFC^VAFCDD01)'="") S VAFCF=".01;" D AVAFC^VAFCDD01(DA)
 S X=DE(4),DIC=DIE
 I $T(KILL^VAFCMIS)'="" D KILL^VAFCMIS(DA)
 S X=DE(4),DIC=DIE
 D:($T(ADGRU^DGRUDD01)'="") ADGRU^DGRUDD01(DA)
C4S S X="" Q:DG(DQ)=X  K DB
 S X=DG(DQ),DIC=DIE
 S ^DPT("B",$E(X,1,30),DA)=""
 S X=DG(DQ),DIC=DIE
 X "Q:$P(^DPT(DA,0),U,9)']""""  S ^DPT(""BS5"",$E(X,1)_$E($P(^(0),U,9),6,9),DA)="""""
 S X=DG(DQ),DIC=DIE
 D EVENT^IVMPLOG(DA)
 S X=DG(DQ),DIC=DIE
 S A1B2TAG="PAT" D ^A1B2XFR
 S X=DG(DQ),DIC=DIE
 X "K DGNEWVAL Q"
 S X=DG(DQ),DIC=DIE
 S IVMX=X,X="IVMPXFR" X ^%ZOSF("TEST") D:$T DPT^IVMPXFR S X=IVMX K IVMX
 S X=DG(DQ),DIC=DIE
 I '$D(DFN),($T(AVAFC^VAFCDD01)'="") S VAFCF=".01;" D AVAFC^VAFCDD01(DA)
 S X=DG(DQ),DIC=DIE
 I $T(SET^VAFCMIS)'="" D SET^VAFCMIS(DA)
 S X=DG(DQ),DIC=DIE
 D:($T(ADGRU^DGRUDD01)'="") ADGRU^DGRUDD01(DA)
C4F1 N X,X1,X2 S DIXR=63 D C4X1(U) K X2 M X2=X D C4X1("O") K X1 M X1=X
 D
 . I $T(ZZKILL^MPIFDEL)'="",X2(1)="" D ZZKILL^MPIFDEL(DA,X2(1))
 K X M X=X2 D
 . I $T(ZZSET^MPIFDEL)'="",$E(X2(1),1,2)="ZZ" D ZZSET^MPIFDEL(DA,X2(1))
 G C4F2
C4X1(DION) K X
 S X(1)=$G(@DIEZTMP@("V",2,DIIENS,.01,DION),$P($G(^DPT(DA,0)),U,1))
 S X=$G(X(1))
 Q
C4F2 Q
X4 K:X[""""!($A(X)=45) X I $D(X) K:$L(X)>30!($L(X)<3)!(X?1P.E)!(X'?1U.ANP)!(X'[",")!(X[":")!(X[";") X I $D(X) D UP^DGHELP S Y=", " S:$D(X)#2 X=$$CLEAN^DPTLK(X) S DGNEWVAL=X
 I $D(X),X'?.ANP K X
 Q
 ;
5 D:$D(DG)>9 F^DIE17,DE S DQ=5,DW="0;2",DV="RSaR",DU="",DLB="SEX",DIFLD=.02
 S DE(DW)="C5^DVBAXA"
 S DU="M:MALE;F:FEMALE;"
 G RE
C5 G C5S:$D(DE(5))[0 K DB
 S X=DE(5),DIC=DIE
 K ^DPT("ASX",$E(X,1,30),DA)
 S X=DE(5),DIC=DIE
 D EVENT^IVMPLOG(DA)
 S X=DE(5),DIC=DIE
 S IVMX=X,IVMKILL=2,X="IVMPXFR" X ^%ZOSF("TEST") D:$T DPT^IVMPXFR S X=IVMX K IVMX,IVMKILL
 S X=DE(5),DIC=DIE
 I ($T(AVAFC^VAFCDD01)'="") S VAFCF=".02;" D AVAFC^VAFCDD01(DA)
 S X=DE(5),DIC=DIE
 D:($T(ADGRU^DGRUDD01)'="") ADGRU^DGRUDD01(DA)
 S X=DE(5),DIIX=2_U_DIFLD D AUDIT^DIET
C5S S X="" Q:DG(DQ)=X  K DB
 S X=DG(DQ),DIC=DIE
 S ^DPT("ASX",$E(X,1,30),DA)=""
 S X=DG(DQ),DIC=DIE
 D EVENT^IVMPLOG(DA)
 S X=DG(DQ),DIC=DIE
 S IVMX=X,X="IVMPXFR" X ^%ZOSF("TEST") D:$T DPT^IVMPXFR S X=IVMX K IVMX
 S X=DG(DQ),DIC=DIE
 I ($T(AVAFC^VAFCDD01)'="") S VAFCF=".02;" D AVAFC^VAFCDD01(DA)
 S X=DG(DQ),DIC=DIE
 D:($T(ADGRU^DGRUDD01)'="") ADGRU^DGRUDD01(DA)
 I $D(DE(5))'[0!(^DD(DP,DIFLD,"AUDIT")'="e") S X=DG(DQ),DIIX=3_U_DIFLD D AUDIT^DIET
 Q
X5 Q
6 D:$D(DG)>9 F^DIE17,DE S DQ=6,DW="0;9",DV="RFXaR",DU="",DLB="SOCIAL SECURITY NUMBER",DIFLD=.09
 S DE(DW)="C6^DVBAXA"
 G RE
C6 G C6S:$D(DE(6))[0 K DB
 S X=DE(6),DIC=DIE
 K ^DPT("BS",$E(X,6,9),DA)
 S X=DE(6),DIC=DIE
 ;
 S X=DE(6),DIC=DIE
 K ^DPT("BS5",$E(^DPT(DA,0),1)_$E(X,6,9),DA)
 S X=DE(6),DIC=DIE
 S A1B2TAG="PAT" D ^A1B2XFR
 S X=DE(6),DIC=DIE
 D KILL^DGREGDD1(DA,.6,0,21,0)
 S X=DE(6),DIC=DIE
 D EVENT^IVMPLOG(DA)
 S X=DE(6),DIC=DIE
 K ^DPT("SSN",$E(X,1,30),DA)
 S X=DE(6),DIC=DIE
 S VADFN=DA D KILL^VADPT6 K VADFN
 S X=DE(6),DIC=DIE
 S PPP=X,X="PPPFMX" X ^%ZOSF("TEST") D:$T KNSSN^PPPFMX S X=PPP K PPP
 S X=DE(6),DIC=DIE
 S IVMX=X,IVMKILL=9,X="IVMPXFR" X ^%ZOSF("TEST") D:$T DPT^IVMPXFR S X=IVMX K IVMX,IVMKILL
 S X=DE(6),DIC=DIE
 S PX=X,X="PXXDPT" X ^%ZOSF("TEST") D:$T KILLSSN^PXXDPT S X=PX K PX
 S X=DE(6),DIC=DIE
 I ($T(AVAFC^VAFCDD01)'="") S VAFCF=".09;" D AVAFC^VAFCDD01(DA)
 S X=DE(6),DIC=DIE
 D:($T(ADGRU^DGRUDD01)'="") ADGRU^DGRUDD01(DA)
 S X=DE(6),DIIX=2_U_DIFLD D AUDIT^DIET
C6S S X="" Q:DG(DQ)=X  K DB
 D ^DVBAXA1
 Q
X6 K:X[""""!($A(X)=45) X I $D(X) S:'$D(DPTX) DFN=DA D SSN^DGINP Q  I $L(X)>10
 I $D(X),X'?.ANP K X
 Q
 ;
7 D:$D(DG)>9 F^DIE17,DE S DQ=7,DW=".31;3",DV="FXOR",DU="",DLB="CLAIM NUMBER",DIFLD=.313
 S DQ(7,2)="S Y(0)=Y S Y=$E(Y,1,10)"
 G RE
X7 S DFN=DA D EV^DGLOCK I $D(X) S L=$S($D(^DPT(DA,0)):$P(^(0),U,9),1:X) W:X?1"SS".E "  ",L S:X?1"SS".E X=L I X'=L K:$L(X)>8!($L(X)<7)!'(X?.N) X
 I $D(X),X'?.ANP K X
 Q
 ;
8 S DW=".31;4",DV="P4'R",DU="",DLB="CLAIM FOLDER LOCATION",DIFLD=.314
 S DE(DW)="C8^DVBAXA"
 S DU="DIC(4,"
 G RE
C8 G C8S:$D(DE(8))[0 K DB
 S X=DE(8),DIC=DIE
 N DGX D CFL4^DGREGDD D KILL^DGREGDD1(DA,.312,.31,2,DGX)
C8S S X="" Q:DG(DQ)=X  K DB
 D ^DVBAXA2
 Q
X8 Q
9 D:$D(DG)>9 F^DIE17,DE S DQ=9,DW=".3;1",DV="RSXa",DU="",DLB="SERVICE CONNECTED?",DIFLD=.301
 S DE(DW)="C9^DVBAXA"
 S DU="Y:YES;N:NO;"
 G RE
C9 G C9S:$D(DE(9))[0 K DB
 D ^DVBAXA3
C9S S X="" Q:DG(DQ)=X  K DB
 D ^DVBAXA4
 Q
X9 S DFN=DA D EV^DGLOCK I $D(X),X="Y" D VET^DGLOCK
 Q
 ;
10 D:$D(DG)>9 F^DIE17,DE S DQ=10,DW=".3;2",DV="NJ3,0Xa",DU="",DLB="SERVICE CONNECTED PERCENTAGE",DIFLD=.302
 S DE(DW)="C10^DVBAXA"
 G RE
C10 G C10S:$D(DE(10))[0 K DB
 D ^DVBAXA5
C10S S X="" Q:DG(DQ)=X  K DB
 D ^DVBAXA6
 Q
X10 S DFN=DA D EV^DGLOCK Q:'$D(X)  K:+X'=X!(X>100)!(X<0)!(X?.E1"."1N.N) X I $D(X),$D(^DPT(DA,.3)),$P(^(.3),U,1)'="Y" W !?4,*7,"Only applies to service-connected applicants." K X
 Q
 ;
11 D:$D(DG)>9 F^DIE17 G ^DVBAXA7
