DVBAXA5 ; ;09/24/12
 S X=DE(14),DIC=DIE
 ;
 S X=DE(14),DIC=DIE
 ;
 S X=DE(14),DIC=DIE
 ;
 S X=DE(14),DIC=DIE
 D AUTOUPD^DGENA2(DA)
 S X=DE(14),DIC=DIE
 X "S DFN=DA D EN^DGMTR K DGREQF"
 S X=DE(14),DIC=DIE
 D EVENT^IVMPLOG(DA)
