DVBAXS ; GENERATED FROM 'DVBA STATUS EDIT' INPUT TEMPLATE(#962), FILE 396;09/19/10
 D DE G BEGIN
DE S DIE="^DVB(396,",DIC=DIE,DP=396,DL=1,DIEL=0,DU="" K DG,DE,DB Q:$O(^DVB(396,DA,""))=""
 I $D(^(0)) S %Z=^(0) S %=$P(%Z,U,9) S:%]"" DE(2)=% S %=$P(%Z,U,10) S:%]"" DE(5)=%,DE(9)=% S %=$P(%Z,U,11) S:%]"" DE(13)=% S %=$P(%Z,U,12) S:%]"" DE(16)=%,DE(20)=% S %=$P(%Z,U,13) S:%]"" DE(24)=% S %=$P(%Z,U,14) S:%]"" DE(27)=%,DE(31)=%
 I  S %=$P(%Z,U,15) S:%]"" DE(35)=%
 I $D(^(1)) S %Z=^(1) S %=$P(%Z,U,2) S:%]"" DE(38)=%,DE(42)=% S %=$P(%Z,U,13) S:%]"" DE(8)=% S %=$P(%Z,U,14) S:%]"" DE(19)=% S %=$P(%Z,U,15) S:%]"" DE(30)=% S %=$P(%Z,U,16) S:%]"" DE(41)=%
 K %Z Q
 ;
W W !?DL+DL-2,DLB_": "
 Q
O D W W Y W:$X>45 !?9
 I $L(Y)>19,'DV,DV'["I",(DV["F"!(DV["K")) G RW^DIR2
 W:Y]"" "// " I 'DV,DV["I",$D(DE(DQ))#2 S X="" W "  (No Editing)" Q
TR R X:DTIME E  S (DTOUT,X)=U W $C(7)
 Q
A K DQ(DQ) S DQ=DQ+1
B G @DQ
RE G PR:$D(DE(DQ)) D W,TR
N I X="" G NKEY:$D(^DD("KEY","F",DP,DIFLD)),A:DV'["R",X:'DV,X:D'>0,A
RD G QS:X?."?" I X["^" D D G ^DIE17
 I X="@" D D G Z^DIE2
 I X=" ",DV["d",DV'["P",$D(^DISV(DUZ,"DIE",DLB)) S X=^(DLB) I DV'["D",DV'["S" W "  "_X
T G M^DIE17:DV,^DIE3:DV["V",P:DV'["S" X:$D(^DD(DP,DIFLD,12.1)) ^(12.1) I X?.ANP D SET I 'DDER X:$D(DIC("S")) DIC("S") I  W:'$D(DB(DQ)) "  "_% G V
 K DDER G X
P I DV["P" S DIC=U_DU,DIC(0)=$E("EN",$D(DB(DQ))+1)_"M"_$E("L",DV'["'") S:DIC(0)["L" DLAYGO=+$P(DV,"P",2) G:DV["*" AST^DIED D NOSCR^DIED S X=+Y,DIC=DIE G X:X<0
 G V:DV'["N" D D I $L($P(X,"."))>24 K X G Z
 I $P(DQ(DQ),U,5)'["$",X?.1"-".N.1".".N,$P(DQ(DQ),U,5,99)["+X'=X" S X=+X
V D @("X"_DQ) K YS
Z K DIC("S"),DLAYGO I $D(X),X'=U D:$G(DE(DW,"INDEX")) SAVEVALS G:'$$KEYCHK UNIQFERR^DIE17 S DG(DW)=X S:DV["d" ^DISV(DUZ,"DIE",DLB)=X G A
X W:'$D(ZTQUEUED) $C(7),"??" I $D(DB(DQ)) G Z^DIE17
 S X="?BAD"
QS S DZ=X D D,QQ^DIEQ G B
D S D=DIFLD,DQ(DQ)=DLB_U_DV_U_DU_U_DW_U_$P($T(@("X"_DQ))," ",2,99) Q
Y I '$D(DE(DQ)) D O G RD:"@"'[X,A:DV'["R"&(X="@"),X:X="@" S X=Y G N
PR S DG=DV,Y=DE(DQ),X=DU I $D(DQ(DQ,2)) X DQ(DQ,2) G RP
R I DG["P",@("$D(^"_X_"0))") S X=+$P(^(0),U,2) G RP:'$D(^(Y,0)) S Y=$P(^(0),U),X=$P(^DD(X,.01,0),U,3),DG=$P(^(0),U,2) G R
 I DG["V",+Y,$P(Y,";",2)["(",$D(@(U_$P(Y,";",2)_"0)")) S X=+$P(^(0),U,2) G RP:'$D(^(+Y,0)) S Y=$P(^(0),U) I $D(^DD(+X,.01,0)) S DG=$P(^(0),U,2),X=$P(^(0),U,3) G R
 X:DG["D" ^DD("DD") I DG["S" S %=$P($P(";"_X,";"_Y_":",2),";") S:%]"" Y=%
RP D O I X="" S X=DE(DQ) G A:'DV,A:DC<2,N^DIE17
I I DV'["I",DV'["#" G RD
 D E^DIE0 G RD:$D(X),PR
 Q
SET N DIR S DIR(0)="SV"_$E("o",$D(DB(DQ)))_U_DU,DIR("V")=1
 I $D(DB(DQ)),'$D(DIQUIET) N DIQUIET S DIQUIET=1
 D ^DIR I 'DDER S %=Y(0),X=Y
 Q
SAVEVALS S @DIEZTMP@("V",DP,DIIENS,DIFLD,"O")=$G(DE(DQ)) S:$D(^("F"))[0 ^("F")=$G(DE(DQ))
 I $D(DE(DW,"4/")) S @DIEZTMP@("V",DP,DIIENS,DIFLD,"4/")=""
 E  K @DIEZTMP@("V",DP,DIIENS,DIFLD,"4/")
 Q
NKEY W:'$D(ZTQUEUED) "??  Required key field" S X="?BAD" G QS
KEYCHK() Q:$G(DE(DW,"KEY"))="" 1 Q @DE(DW,"KEY")
BEGIN S DNM="DVBAXS",DQ=1
 N DIEZTMP,DIEZAR,DIEZRXR,DIIENS,DIXR K DIEFIRE,DIEBADK S DIEZTMP=$$GETTMP^DIKC1("DIEZ")
 M DIEZAR=^DIE(962,"AR") S DICRREC="TRIG^DIE17"
 S:$D(DTIME)[0 DTIME=300 S D0=DA,DIIENS=DA_",",DIEZ=962,U="^"
1 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=1 D X1 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X1 S CODE=$P(^DVB(396,D0,0),U,9) S:CODE="" Y="@2" S:DVBACORR="N"&(CODE'="P") Y="@2"
 Q
2 S DW="0;9",DV="S",DU="",DLB="NOTICE/DISCHG STATUS",DIFLD=4.5
 S DU="P:PENDING;C:COMPLETED;"
 G RE
X2 Q
3 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=3 D X3 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X3 S DVBASTAT=X S:X="C" Y="@1"
 Q
4 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=4 D X4 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X4 S DVBADT=$P(^DVB(396,D0,0),U,10) S:DVBADT=""&(X="P") Y="@2"
 Q
5 S DW="0;10",DV="D",DU="",DLB="NOTICE/DISCHG COMPLETION DATE",DIFLD=4.8
 S Y="@"
 S X=Y,DB(DQ)=1 G:X="" N^DIE17:DV,A I $D(DE(DQ)),DV["I"!(DV["#") D E^DIE0 G A:'$D(X)
 G RD
X5 S %DT="X" D ^%DT S X=Y K:Y<1 X
 Q
 ;
6 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=6 D X6 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X6 S Y="@2"
 Q
7 S DQ=8 ;@1
8 S DW="1;13",DV="F",DU="",DLB="EDIT4.5",DIFLD=4.9
 S X=OPER
 S Y=X
 S X=Y,DB(DQ)=1,DE(DW,"4/")="" G:X="" N^DIE17:DV,A I $D(DE(DQ)),DV["I"!(DV["#") D E^DIE0 G A:'$D(X)
 G RD:X="@",Z
X8 Q
9 S DW="0;10",DV="D",DU="",DLB="NOTICE/DISCHG COMPLETION DATE",DIFLD=4.8
 G RE
X9 S %DT="EX" D ^%DT S X=Y K:Y<1 X
 Q
 ;
10 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=10 D X10 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X10 I X=""&(DVBASTAT="C") W !!,"Completed status must have date.",*7,!! S Y="@1"
 Q
11 S DQ=12 ;@2
12 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=12 D X12 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X12 S CODE=$P(^DVB(396,D0,0),U,11) S:CODE="" Y="@4" S:DVBACORR="N"&(CODE'="P") Y="@4"
 Q
13 S DW="0;11",DV="S",DU="",DLB="HOSPITAL SUMMARY STATUS",DIFLD=5.5
 S DU="P:PENDING;C:COMPLETED;"
 G RE
X13 Q
14 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=14 D X14 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X14 S DVBASTAT=X S:X="C" Y="@3"
 Q
15 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=15 D X15 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X15 S DVBADT=$P(^DVB(396,D0,0),U,12) S:DVBADT=""&(X="P") Y="@4"
 Q
16 S DW="0;12",DV="D",DU="",DLB="HOSP SUMMARY COMPLETION DATE",DIFLD=5.8
 S Y="@"
 S X=Y,DB(DQ)=1 G:X="" N^DIE17:DV,A I $D(DE(DQ)),DV["I"!(DV["#") D E^DIE0 G A:'$D(X)
 G RD
X16 S %DT="X" D ^%DT S X=Y K:Y<1 X
 Q
 ;
17 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=17 D X17 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X17 S Y="@4"
 Q
18 S DQ=19 ;@3
19 S DW="1;14",DV="F",DU="",DLB="EDIT5.5",DIFLD=5.9
 S X=OPER
 S Y=X
 S X=Y,DB(DQ)=1,DE(DW,"4/")="" G:X="" N^DIE17:DV,A I $D(DE(DQ)),DV["I"!(DV["#") D E^DIE0 G A:'$D(X)
 G RD:X="@",Z
X19 Q
20 S DW="0;12",DV="D",DU="",DLB="HOSP SUMMARY COMPLETION DATE",DIFLD=5.8
 G RE
X20 S %DT="EX" D ^%DT S X=Y K:Y<1 X
 Q
 ;
21 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=21 D X21 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X21 I X=""&(DVBASTAT="C") W *7,!!,"Completed status must have date.",!! S Y="@3"
 Q
22 S DQ=23 ;@4
23 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=23 D X23 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X23 S CODE=$P(^DVB(396,D0,0),U,13) S:CODE="" Y="@6" S:DVBACORR="N"&(CODE'="P") Y="@6"
 Q
24 S DW="0;13",DV="S",DU="",DLB="(21-DAY) CERTIFICATE STATUS",DIFLD=6.5
 S DU="P:PENDING;C:COMPLETED;"
 G RE
X24 Q
25 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=25 D X25 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X25 S DVBASTAT=X S:X="C" Y="@5"
 Q
26 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=26 D X26 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X26 S DVBADT=$P(^DVB(396,D0,0),U,14) S:DVBADT=""&(X="P") Y="@6"
 Q
27 S DW="0;14",DV="D",DU="",DLB="(21-DAY) COMPLETION DATE",DIFLD=6.8
 S Y="@"
 S X=Y,DB(DQ)=1 G:X="" N^DIE17:DV,A I $D(DE(DQ)),DV["I"!(DV["#") D E^DIE0 G A:'$D(X)
 G RD
X27 S %DT="X" D ^%DT S X=Y K:Y<1 X
 Q
 ;
28 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=28 D X28 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X28 S Y="@6"
 Q
29 S DQ=30 ;@5
30 S DW="1;15",DV="F",DU="",DLB="EDIT6.5",DIFLD=6.9
 S X=OPER
 S Y=X
 S X=Y,DB(DQ)=1,DE(DW,"4/")="" G:X="" N^DIE17:DV,A I $D(DE(DQ)),DV["I"!(DV["#") D E^DIE0 G A:'$D(X)
 G RD:X="@",Z
X30 Q
31 S DW="0;14",DV="D",DU="",DLB="(21-DAY) COMPLETION DATE",DIFLD=6.8
 G RE
X31 S %DT="EX" D ^%DT S X=Y K:Y<1 X
 Q
 ;
32 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=32 D X32 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X32 I X=""&(DVBASTAT="C") W *7,!!,"Completed status must have date.",!! S Y="@5"
 Q
33 S DQ=34 ;@6
34 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=34 D X34 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X34 S CODE=$P(^DVB(396,D0,0),U,15) S:CODE="" Y="@8" S:DVBACORR="N"&(CODE'="P") Y="@8"
 Q
35 S DW="0;15",DV="S",DU="",DLB="STATUS OF OTHER/EXAM",DIFLD=8
 S DU="P:PENDING;C:COMPLETED;"
 G RE
X35 Q
36 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=36 D X36 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X36 S DVBASTAT=X S:X="C" Y="@7"
 Q
37 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=37 D X37 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X37 S DVBADT=$S($D(^DVB(396,D0,1)):$P(^(1),U,2),1:"") S:DVBADT=""&(X="P") Y="@8"
 Q
38 S DW="1;2",DV="D",DU="",DLB="OTHER/EXAM COMPLETION DATE",DIFLD=8.5
 S Y="@"
 S X=Y,DB(DQ)=1 G:X="" N^DIE17:DV,A I $D(DE(DQ)),DV["I"!(DV["#") D E^DIE0 G A:'$D(X)
 G RD
X38 S %DT="X" D ^%DT S X=Y K:Y<1 X
 Q
 ;
39 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=39 D X39 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X39 S Y="@8"
 Q
40 S DQ=41 ;@7
41 S DW="1;16",DV="F",DU="",DLB="EDIT8",DIFLD=8.7
 S X=OPER
 S Y=X
 S X=Y,DB(DQ)=1,DE(DW,"4/")="" G:X="" N^DIE17:DV,A I $D(DE(DQ)),DV["I"!(DV["#") D E^DIE0 G A:'$D(X)
 G RD:X="@",Z
X41 Q
42 S DW="1;2",DV="D",DU="",DLB="OTHER/EXAM COMPLETION DATE",DIFLD=8.5
 G RE
X42 S %DT="EX" D ^%DT S X=Y K:Y<1 X
 Q
 ;
43 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=43 D X43 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X43 I X=""&(DVBASTAT="C") W *7,!!,"Completed status must have date.",!! S Y="@7"
 Q
44 S DQ=45 ;@8
45 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=45 D X45 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X45 S CODE=$P(^DVB(396,D0,0),U,17) S:CODE="" Y="@10" S:DVBACORR="N"&(CODE'="P") Y="@10"
 Q
46 D:$D(DG)>9 F^DIE17 G ^DVBAXS1
