RMPRP23 ;PHX/RFM-PRINT 10-2421 ;8/29/1994
 ;;3.0;PROSTHETICS;;Feb 09, 1996
PRI ;ENTRY POINT FOR PRINTING PRIVACY ACT FOR 10-2421 AND 10-55 AND 2419
 W @IOF,"52.224-2 PRIVACY ACT (APR 1984)",!!,"(a)  The Contractor agrees to---",!?3,"(1) Comply with the Privacy Act of 1974 (the Act) and the agency rules and"
 W !,"regulations issued under the Act in the design, development, or operation "
 W !,"of any system of records on individuals to accomplish an agency function when"
 W !,"the contract specifically identifies---"
 W !?5,"(i)  The systems of records: and",!?5,"(ii) The design, development, or operation work that the contractor is to",!," perform;"
 W !?3,"(2) Include the Privacy Act notification contained in this contract in every"
 W !,"solicitation and resulting subcontract and in every subcontract awarded without"
 W !,"a solicitation, when the work statement in the proposed subcontract required the"
 W !,"redesign, development, or operation of a system of records on individuals that"
 W !,"is subject to the Act; and"
 W !?3,"(3) Include this clause, including this subparagraph (3), in all subcontracts"
 W !,"awarded under this contract which requires the design, development, or opera-"
 W !,"tion of such a system of records."
 W !,"(b)  In the event of violations of the Act, a civil action may be brought ag-"
 W !,"ainst the agency involved when the violation concerns the design, development or"
PRIV W !,"operation of a system of records on individuals to accomplish an agency function,"
 W !,"and criminal penalties may be imposed upon the officers or employees of the ag-"
 W !,"ency when the violation concerns the operation of a system of records on indivi-"
 W !,"duals to accomplish an agency function. For purposes of the Act, when the con-"
 W !,"tract is for the operation of a system of records on individuals to accomplish"
 W !,"an agency function, the Contractor is considered to be an employee of the agen-"
 W !,"cy."
 W !,"(c) (1)  ""Operation of a system of records,"" as used in this clause, means per-"
 W !,"formance of any of the activities associated with maintaining the system of re-"
 W !,"cords, including the collection, use, and dissemination of records."
 W !?5,"(2) ""Record,"" as used in this clause, means any item, collection, or grouping"
 W !,"of information about an individual that is maintained by an agency, including,"
 W !,"but not limited to, education, financial transactions, medical history, and"
 W !,"criminal or employment history and that contains the person's name, or the iden-"
 W !,"tifying number, symbol, or other identifying particular assigned to the indivi-"
 W !,"dual, such as a fingerprint or voiceprint or a photograph."
 W !?5,"(3) ""System of records on individuals"" as used in this clause, means a"
 W !,"group of any records under the control of any agency from which information is"
 W !,"retrieved by the name of the individual or by some identifying number, symbol,"
 W !,"or other identifying particular assigned to the individual."
 Q
