IMRLUTIL ;HCIOFO/FAI-LOCAL UTILIZATION SUMMARY ;05/18/00  17:26
 ;;2.1;IMMUNOLOGY CASE REGISTRY;**5**;Feb 09, 1998
ENTRY ;[IMR PATIENT LIST] - Local Registry List - ICR Patients
 W !,?10,"####################################################"
 W !,?10,"#",?20,"Summary Utilization Data",?61,"#"
 W !,?10,"####################################################"
 D ^IMRDATE
 S IMR2C=1,IMRRMAX=50,IMRN2=10,IMRN1=2
 S IMRSD=IMRHNBEG,IMRED=IMRHNEND
CAT S DIR(0)="Y",DIR("A")="Do you want the list sorted by Category (Y/N)?",DIR("B")="NO",DIR("?")="Answer YES to sort by HIV CATEGORY." D ^DIR K DIR S IMR2C=Y
 I IMR2C'=0 G DEV
 ;  IF LISTING BY CATEGORY IS NO GIVE THE FOLLOWING PROMPT
REIM S REIM="N" R !!,"Do you want the list sorted by Reimbursement Level (Y/N)? N// ",X:DTIME G:'$T!(X[U) KILL S:X="" X="N" I "Yy"[$E(X) S REIM="Y"
 I "YyNn"'[$E(X) W $C(7),"  ??",!!,"Enter YES or NO" G REIM
DEV D IMRDEV^IMREDIT
 G:POP KILL
 I '$D(IO("Q")) D DQ Q
 I $D(IO("Q")) D  G KILL
 .S ZTRTN="DQ^IMRLUTIL",IOP="Q",ZTDESC="Immunology Summary Utilization Data"
 .S ZTSAVE("*")="",ZTIO=ION_";"_IOM_";"_IOSL
 .D ^%ZTLOAD K ZTRTN,ZTDESC,ZTSAVE,ZTSK
 .Q
DQ D ^IMRSUDRX,^IMRSUDOP,^IMRSUDLB,^IMRSUDRA,KILL
 Q
KILL D ^%ZISC K IMRSD,IMRK,IMRED,IMREDP1,IMRX,IMRD,IMRAD,IMRDD,IMRBS,IMRCS,IMRCSN,IMRD1,IMRDAYS,IMRDFN,IMRI,IMRJ,IMRK,IMRN,IMRUT,IMRRMAX,IMR0C,IMR1C,IMR2C,IMRLBL,IMRAD1,IMRDX,IMRFLG,IMRL,IMRNAM,IMRSDV,IMRSDVA,IMRSSN,IMRZ,IMRDY
 K IMRFLG,IMRDTH,IMRBSO,%I,%T,I,J,K,K1,L,POP,V,X,X1,X2,Y,Z,Z1,DIR,^TMP($J),VAERR,D,IMRPG,DIRUT,DTOUT,DUOUT,DIROUT,IMRALOS,DISYS,IMRDISP,IMRDSP,IMRDTE,IMREC,IMRFB,IMROUT,IMRPTF,IMRST,IMRSUF
 D ^%ZISC
 Q
