DVB464A ;ALB/MJB - DISABILITY FILE UPDATE ; 6/28/10 1:34pm
        ;;4.0;HINQ;**64**;03/25/92;Build 25
        ;
        ;This routine will be run as a post-installation for patch DVB*4*64
        ;This routine will update the disability condition file to add requested
        ;disability conditions.
        ;
        Q
        ;
POST(DVBTMP,DVBTOT)     ;entry point
        N DVBLINE
         ;  Input:
        ;    DVBTMP - Closed Root global reference for error reporting
        ;    DVBTOT - Total number of ICD9 codes filed
        ;
        ;  Output:
        ;    DVBTMP - Temp file of error messages (if any)
        ;    DVBTOT - Total number of ICD9 codes filed
        ;
        N DVBRTN,DVBCNT
        S DVBTMP=$G(DVBTMP)
        S DVBTOT=$G(DVBTOT) I DVBTOT']"" S DVBTOT=0
        I DVBTMP']"" S DVBTMP=$NA(^TMP("DVB464P",$J)) K @DVBTMP
        ;
        ;
DVBNEW  ;add new codes or modify name if code is in use
        ;
        N DVBLINE
        S DVBLINE=1
        F DVBI=DVBLINE:1 S DVBJ=$P($T(NEWCODE+DVBI),";;",2) Q:DVBJ["$EXIT"  D
        .S DVBCODE=+DVBJ,DVBNAME=$E($P(DVBJ,"^",2),1,45),DVBLINE=DVBI
        .S DVBDESC=$E($P(DVBJ,"^",3),1,200)
        .;
        .;add new code
        .I '$D(^DIC(31,"C",DVBCODE)) D
        ..K DD,DO
        ..S DIC="^DIC(31,",DIC(0)="L",DIC("DR")="2////"_DVBCODE_";10////"_DVBDESC
        ..S X=DVBNAME,DLAYGO=31
        ..D FILE^DICN
        ..D MES^XPDUTL(DVBCODE_":  adding  "_DVBCODE_"  "_X)
        ..K DLAYGO,DIC,X
        ..Q
        .;
        .;modify name
        .S DVBIEN=+$O(^DIC(31,"C",DVBCODE,0))
        .S DVBREC=$G(^DIC(31,DVBIEN,0)),DVBOLDSC=$G(^DIC(31,DVBIEN,1)) I DVBREC']"" D
        ..D MES^XPDUTL("  >>>> error "_DVBCODE_" in C x-reference and not in file 31")
        ..Q
        .S DVBOLDN=$P(DVBREC,"^") I DVBOLDN'=DVBNAME!(DVBOLDSC'=DVBDESC) D
        ..S DA=DVBIEN,DIE="^DIC(31,",DR=".01////"_DVBNAME_";10////"_DVBDESC
        ..D ^DIE
        ..K DR,DA,DIE
        ..D MES^XPDUTL(DVBCODE_": changing name from "_DVBOLDN)
        ..D MES^XPDUTL("                    to   "_DVBNAME)
        ..D MES^XPDUTL(DVBCODE_": changing description...")
        ..D MES^XPDUTL("          from:  "_DVBOLDSC)
        ..D MES^XPDUTL("            to:  "_DVBDESC)
        .;
        K DVBCODE,DVBI,DVBIEN,DVBJ,DVBNAME,DVBOLDN,DVBREC,DVBDESC,DVBOLDSC
        Q
        ;
NEWCODE ;codes to be added or changed
        ;;6036^STATUS POST CORNEAL TRANSPLANT^STATUS POST CORNEAL TRANSPLANT
        ;;6037^PINGUECULA, SPOT ON WHITE OF EYE^PINGUECULA, SPOT ON WHITE OF EYE
        ;;8850^UNDIAG. COND. - MUSCULOSKELETAL SYSTEM^UNDIAG. COND. - MUSCULOSKELETAL SYSTEM
        ;;8851^UNDIAG. COND. - AMPUTATIONS^UNDIAG. COND. - AMPUTATIONS
        ;;8852^UNDIAG. COND. - JOINTS, SKULL AND RIBS^UNDIAG. COND. - JOINTS, SKULL AND RIBS
        ;;8853^UNDIAG. COND. - MUSCLE^UNDIAG. COND. - MUSCLE
        ;;8860^UNDIAG. COND. - EYE DISEASE^UNDIAG. COND. - EYE DISEASE
        ;;8861^UNDIAG. COND. - HEARING LOSS^UNDIAG. COND. - HEARING LOSS
        ;;8862^UNDIAG. COND. - EAR AND OTHER SENSE ORGAN^UNDIAG. COND. - EAR AND OTHER SENSE ORGAN
        ;;8863^UNDIAG. COND. - SYSTEMIC DISEASES^UNDIAG. COND. - SYSTEMIC DISEASES
        ;;8865^UNDIAG. COND. - NOSE AND THROAT^UNDIAG. COND. - NOSE AND THROAT
        ;;8866^UNDIAG. COND. - TRACHEA AND BRONCHI^UNDIAG. COND. - TRACHEA AND BRONCHI
        ;;8867^UNDIAG. COND. - TUBERCULOSIS^UNDIAG. COND. - TUBERCULOSIS
        ;;8868^UNDIAG. COND. - LUNGS AND PLEURA^UNDIAG. COND. - LUNGS AND PLEURA
        ;;8870^UNDIAG. COND. - HEART DISEASE^UNDIAG. COND. - HEART DISEASE
        ;;8871^UNDIAG. COND. - ARTERIES AND VEINS^UNDIAG. COND. - ARTERIES AND VEINS
        ;;8872^UNDIAG. COND. - UPPER DIGESTIVE SYSTEM^UNDIAG. COND. - UPPER DIGESTIVE SYSTEM
        ;;8873^UNDIAG. COND. - LOWER DIGESTIVE SYSTEM^UNDIAG. COND. - LOWER DIGESTIVE SYSTEM
        ;;8875^UNDIAG. COND. - GENITOURINARY SYSTEM^UNDIAG. COND. - GENITOURINARY SYSTEM
        ;;8876^UNDIAG. COND. - GYNECOLOGICAL SYSTEM^UNDIAG. COND. - GYNECOLOGICAL SYSTEM
        ;;8877^UNDIAG. COND. - HEMIC AND LYMPHATIC SYSTEM^UNDIAG. COND. - HEMIC AND LYMPHATIC SYSTEM
        ;;8878^UNDIAG. COND. - SKIN^UNDIAG. COND. - SKIN
        ;;8879^UNDIAG. COND. - ENDOCRINE SYSTEM^UNDIAG. COND. - ENDOCRINE SYSTEM
        ;;8880^UNDIAG. COND. - CENTRAL NERVOUS SYSTEM^UNDIAG. COND. - CENTRAL NERVOUS SYSTEM
        ;;8881^UNDIAG. COND. - MISC NEUROLOGICAL^UNDIAG. COND. - MISC NEUROLOGICAL
        ;;8882^UNDIAG. COND. - CRANIAL NERVE PARALYSIS^UNDIAG. COND. - CRANIAL NERVE PARALYSIS
        ;;8883^UNDIAG. COND. - CRANIAL NERVE NEURITIS^UNDIAG. COND. - CRANIAL NERVE NEURITIS
        ;;8884^UNDIAG. COND. - CRANIAL NERVE NEURALGIA^UNDIAG. COND. - CRANIAL NERVE NEURALGIA
        ;;8885^UNDIAG. COND. - PERIPHERAL NERVE PARALYSIS^UNDIAG. COND. - PERIPHERAL NERVE PARALYSIS
        ;;8886^UNDIAG. COND. - PERIPHERAL NERVE NEURITIS^UNDIAG. COND. - PERIPHERAL NERVE NEURITIS
        ;;8887^UNDIAG. COND. - PERIPHERAL NERVE NEURALGIA^UNDIAG. COND. - PERIPHERAL NERVE NEURALGIA
        ;;8889^UNDIAG. COND. - EPILEPSIES^UNDIAG. COND. - EPILEPSIES
        ;;8892^UNDIAG. COND. - PSYCHOTIC DISORDERS^UNDIAG. COND. - PSYCHOTIC DISORDERS
        ;;8893^UNDIAG. COND. - ORGANIC MENTAL DISORDERS^UNDIAG. COND. - ORGANIC MENTAL DISORDERS
        ;;8894^UNDIAG. COND. - PSYCHONEUROTIC DISORDERS^UNDIAG. COND. - PSYCHONEUROTIC DISORDERS
        ;;8895^UNDIAG. COND. - PSYCHOPHYSIOLOGIC DISORDER^UNDIAG. COND. - PSYCHOPHYSIOLOGIC DISORDER
        ;;8899^UNDIAG. COND. - DENTAL AND ORAL CONDITION^UNDIAG. COND. - DENTAL AND ORAL CONDITION
        ;;9007^PSYCHOSIS^PSYCHOSIS
        ;;$EXIT
        Q
